<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Authentication;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\OauthToken;

/**
 * Utility class for initializing Oauth2 security credentials.
 */
class Oauth2CredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for Oauth2CredentialsBuilder
     *
     * @param string $oauthClientId
     * @param string $oauthClientSecret
     * @param string $oauthRedirectUri
     */
    public static function init(string $oauthClientId, string $oauthClientSecret, string $oauthRedirectUri): self
    {
        return new self([
            'oauthClientId' => $oauthClientId,
            'oauthClientSecret' => $oauthClientSecret,
            'oauthRedirectUri' => $oauthRedirectUri
        ]);
    }

    /**
     * Setter for OauthClientId.
     *
     * @param string $oauthClientId
     *
     * @return $this
     */
    public function oauthClientId(string $oauthClientId): self
    {
        $this->config['oauthClientId'] = $oauthClientId;
        return $this;
    }

    /**
     * Setter for OauthClientSecret.
     *
     * @param string $oauthClientSecret
     *
     * @return $this
     */
    public function oauthClientSecret(string $oauthClientSecret): self
    {
        $this->config['oauthClientSecret'] = $oauthClientSecret;
        return $this;
    }

    /**
     * Setter for OauthRedirectUri.
     *
     * @param string $oauthRedirectUri
     *
     * @return $this
     */
    public function oauthRedirectUri(string $oauthRedirectUri): self
    {
        $this->config['oauthRedirectUri'] = $oauthRedirectUri;
        return $this;
    }

    /**
     * Setter for OauthToken.
     *
     * @param OauthToken|null $oauthToken
     *
     * @return $this
     */
    public function oauthToken(?OauthToken $oauthToken): self
    {
        $this->config['oauthToken'] = $oauthToken;
        return $this;
    }

    /**
     * Setter for clock skew time in seconds applied while checking the OAuth Token expiry.
     *
     * @param int $oauthClockSkew
     *
     * @return $this
     */
    public function oauthClockSkew(int $oauthClockSkew): self
    {
        $this->config['oauth2-ClockSkew'] = $oauthClockSkew;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
