<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Authentication;

use TeslaFleetManagementApiLib\Models\OAuthToken;

/**
 * Interface for defining the behavior of Authentication.
 */
interface Oauth2Credentials
{
    /**
     * String value for oauthClientId.
     */
    public function getOauthClientId(): string;

    /**
     * String value for oauthClientSecret.
     */
    public function getOauthClientSecret(): string;

    /**
     * String value for oauthRedirectUri.
     */
    public function getOauthRedirectUri(): string;

    /**
     * OauthToken value for oauthToken.
     */
    public function getOauthToken(): ?OauthToken;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $oauthClientId OAuth 2 Client ID
     * @param string $oauthClientSecret OAuth 2 Client Secret
     * @param string $oauthRedirectUri OAuth 2 Redirection endpoint or Callback Uri
     */
    public function equals(string $oauthClientId, string $oauthClientSecret, string $oauthRedirectUri): bool;

    /**
     * Build an authorization URL for taking the user's consent to access data.
     *
     * @param string|null $state An opaque state string.
     * @param array|null $additionalParams Additional parameters to be sent.
     */
    public function buildAuthorizationUrl(?string $state = null, ?array $additionalParams = null): string;

    /**
     * Refresh the OAuth token.
     *
     * @param array|null $additionalParams Additional parameters to be sent.
     */
    public function refreshToken(?array $additionalParams = null): OAuthToken;

    /**
     * Fetch the OAuth token.
     *
     * @param string $authorizationCode Authorization code returned by the OAuth provider.
     * @param array|null $additionalParams Additional parameters to be sent.
     */
    public function fetchToken(string $authorizationCode, ?array $additionalParams = null): OAuthToken;

    /**
     * Has the OAuth token expired? If the token argument is not provided then this function will check the
     * expiry of the initial oauthToken, that's set in the client initialization.
     */
    public function isTokenExpired(?OAuthToken $token = null): bool;
}
