<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ActuateTrunkRequest;

/**
 * Builder for model ActuateTrunkRequest
 *
 * @see ActuateTrunkRequest
 */
class ActuateTrunkRequestBuilder
{
    /**
     * @var ActuateTrunkRequest
     */
    private $instance;

    private function __construct(ActuateTrunkRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Actuate Trunk Request Builder object.
     *
     * @param string $whichTrunk
     */
    public static function init(string $whichTrunk): self
    {
        return new self(new ActuateTrunkRequest($whichTrunk));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Actuate Trunk Request object.
     */
    public function build(): ActuateTrunkRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
