<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\AddChargeScheduleRequest;

/**
 * Builder for model AddChargeScheduleRequest
 *
 * @see AddChargeScheduleRequest
 */
class AddChargeScheduleRequestBuilder
{
    /**
     * @var AddChargeScheduleRequest
     */
    private $instance;

    private function __construct(AddChargeScheduleRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Add Charge Schedule Request Builder object.
     *
     * @param float $lat
     * @param float $lon
     * @param int $id
     * @param bool $enabled
     */
    public static function init(float $lat, float $lon, int $id, bool $enabled): self
    {
        return new self(new AddChargeScheduleRequest($lat, $lon, $id, $enabled));
    }

    /**
     * Sets days of week field.
     *
     * @param string|null $value
     */
    public function daysOfWeek(?string $value): self
    {
        $this->instance->setDaysOfWeek($value);
        return $this;
    }

    /**
     * Sets start enabled field.
     *
     * @param bool|null $value
     */
    public function startEnabled(?bool $value): self
    {
        $this->instance->setStartEnabled($value);
        return $this;
    }

    /**
     * Sets start time field.
     *
     * @param int|null $value
     */
    public function startTime(?int $value): self
    {
        $this->instance->setStartTime($value);
        return $this;
    }

    /**
     * Sets end enabled field.
     *
     * @param bool|null $value
     */
    public function endEnabled(?bool $value): self
    {
        $this->instance->setEndEnabled($value);
        return $this;
    }

    /**
     * Sets end time field.
     *
     * @param int|null $value
     */
    public function endTime(?int $value): self
    {
        $this->instance->setEndTime($value);
        return $this;
    }

    /**
     * Sets one time field.
     *
     * @param bool|null $value
     */
    public function oneTime(?bool $value): self
    {
        $this->instance->setOneTime($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Add Charge Schedule Request object.
     */
    public function build(): AddChargeScheduleRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
