<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Api1DxWarrantyDetailsResponse;
use TeslaFleetManagementApiLib\Models\ResponseApi1DxWarrantyDetailsResponse;

/**
 * Builder for model Api1DxWarrantyDetailsResponse
 *
 * @see Api1DxWarrantyDetailsResponse
 */
class Api1DxWarrantyDetailsResponseBuilder
{
    /**
     * @var Api1DxWarrantyDetailsResponse
     */
    private $instance;

    private function __construct(Api1DxWarrantyDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api 1 Dx Warranty Details Response Builder object.
     */
    public static function init(): self
    {
        return new self(new Api1DxWarrantyDetailsResponse());
    }

    /**
     * Sets response field.
     *
     * @param ResponseApi1DxWarrantyDetailsResponse|null $value
     */
    public function response(?ResponseApi1DxWarrantyDetailsResponse $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api 1 Dx Warranty Details Response object.
     */
    public function build(): Api1DxWarrantyDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
