<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Api1VehiclesResponse;
use TeslaFleetManagementApiLib\Models\Pagination;
use TeslaFleetManagementApiLib\Models\VehicleBase;

/**
 * Builder for model Api1VehiclesResponse
 *
 * @see Api1VehiclesResponse
 */
class Api1VehiclesResponseBuilder
{
    /**
     * @var Api1VehiclesResponse
     */
    private $instance;

    private function __construct(Api1VehiclesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api 1 Vehicles Response Builder object.
     */
    public static function init(): self
    {
        return new self(new Api1VehiclesResponse());
    }

    /**
     * Sets response field.
     *
     * @param VehicleBase[]|null $value
     */
    public function response(?array $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Sets pagination field.
     *
     * @param Pagination|null $value
     */
    public function pagination(?Pagination $value): self
    {
        $this->instance->setPagination($value);
        return $this;
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api 1 Vehicles Response object.
     */
    public function build(): Api1VehiclesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
