<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Api1VehiclesNearbyChargingSitesResponse;
use TeslaFleetManagementApiLib\Models\Response3;

/**
 * Builder for model Api1VehiclesNearbyChargingSitesResponse
 *
 * @see Api1VehiclesNearbyChargingSitesResponse
 */
class Api1VehiclesNearbyChargingSitesResponseBuilder
{
    /**
     * @var Api1VehiclesNearbyChargingSitesResponse
     */
    private $instance;

    private function __construct(Api1VehiclesNearbyChargingSitesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api 1 Vehicles Nearby Charging Sites Response Builder object.
     */
    public static function init(): self
    {
        return new self(new Api1VehiclesNearbyChargingSitesResponse());
    }

    /**
     * Sets response field.
     *
     * @param Response3|null $value
     */
    public function response(?Response3 $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api 1 Vehicles Nearby Charging Sites Response object.
     */
    public function build(): Api1VehiclesNearbyChargingSitesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
