<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Api1VehiclesMobileEnabledResponse;
use TeslaFleetManagementApiLib\Models\MobileEnabled;

/**
 * Builder for model Api1VehiclesMobileEnabledResponse
 *
 * @see Api1VehiclesMobileEnabledResponse
 */
class Api1VehiclesMobileEnabledResponseBuilder
{
    /**
     * @var Api1VehiclesMobileEnabledResponse
     */
    private $instance;

    private function __construct(Api1VehiclesMobileEnabledResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api 1 Vehicles Mobile Enabled Response Builder object.
     */
    public static function init(): self
    {
        return new self(new Api1VehiclesMobileEnabledResponse());
    }

    /**
     * Sets response field.
     *
     * @param MobileEnabled|null $value
     */
    public function response(?MobileEnabled $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api 1 Vehicles Mobile Enabled Response object.
     */
    public function build(): Api1VehiclesMobileEnabledResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
