<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Api1VehiclesWakeUpResponse;
use TeslaFleetManagementApiLib\Models\VehicleBase;

/**
 * Builder for model Api1VehiclesWakeUpResponse
 *
 * @see Api1VehiclesWakeUpResponse
 */
class Api1VehiclesWakeUpResponseBuilder
{
    /**
     * @var Api1VehiclesWakeUpResponse
     */
    private $instance;

    private function __construct(Api1VehiclesWakeUpResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api 1 Vehicles Wake Up Response Builder object.
     */
    public static function init(): self
    {
        return new self(new Api1VehiclesWakeUpResponse());
    }

    /**
     * Sets response field.
     *
     * @param VehicleBase|null $value
     */
    public function response(?VehicleBase $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api 1 Vehicles Wake Up Response object.
     */
    public function build(): Api1VehiclesWakeUpResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
