<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Api1DxVehiclesOptionsResponse;
use TeslaFleetManagementApiLib\Models\ResponseApi1DxVehiclesOptionsResponse;

/**
 * Builder for model Api1DxVehiclesOptionsResponse
 *
 * @see Api1DxVehiclesOptionsResponse
 */
class Api1DxVehiclesOptionsResponseBuilder
{
    /**
     * @var Api1DxVehiclesOptionsResponse
     */
    private $instance;

    private function __construct(Api1DxVehiclesOptionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api 1 Dx Vehicles Options Response Builder object.
     */
    public static function init(): self
    {
        return new self(new Api1DxVehiclesOptionsResponse());
    }

    /**
     * Sets response field.
     *
     * @param ResponseApi1DxVehiclesOptionsResponse|null $value
     */
    public function response(?ResponseApi1DxVehiclesOptionsResponse $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api 1 Dx Vehicles Options Response object.
     */
    public function build(): Api1DxVehiclesOptionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
