<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\BackupResponse;
use TeslaFleetManagementApiLib\Models\Response;

/**
 * Builder for model BackupResponse
 *
 * @see BackupResponse
 */
class BackupResponseBuilder
{
    /**
     * @var BackupResponse
     */
    private $instance;

    private function __construct(BackupResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Backup Response Builder object.
     *
     * @param Response $response
     */
    public static function init(Response $response): self
    {
        return new self(new BackupResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Backup Response object.
     */
    public function build(): BackupResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
