<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\BackupRequest;

/**
 * Builder for model BackupRequest
 *
 * @see BackupRequest
 */
class BackupRequestBuilder
{
    /**
     * @var BackupRequest
     */
    private $instance;

    private function __construct(BackupRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Backup Request Builder object.
     *
     * @param int $backupReservePercent
     */
    public static function init(int $backupReservePercent): self
    {
        return new self(new BackupRequest($backupReservePercent));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Backup Request object.
     */
    public function build(): BackupRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
