<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\CalendarHistoryResponse;
use TeslaFleetManagementApiLib\Models\ResponseCalendarHistoryResponse;

/**
 * Builder for model CalendarHistoryResponse
 *
 * @see CalendarHistoryResponse
 */
class CalendarHistoryResponseBuilder
{
    /**
     * @var CalendarHistoryResponse
     */
    private $instance;

    private function __construct(CalendarHistoryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar History Response Builder object.
     *
     * @param ResponseCalendarHistoryResponse $response
     */
    public static function init(ResponseCalendarHistoryResponse $response): self
    {
        return new self(new CalendarHistoryResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar History Response object.
     */
    public function build(): CalendarHistoryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
