<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingFee;
use TeslaFleetManagementApiLib\Models\ChargingHistoryItem;
use TeslaFleetManagementApiLib\Models\ChargingInvoice;

/**
 * Builder for model ChargingHistoryItem
 *
 * @see ChargingHistoryItem
 */
class ChargingHistoryItemBuilder
{
    /**
     * @var ChargingHistoryItem
     */
    private $instance;

    private function __construct(ChargingHistoryItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging History Item Builder object.
     *
     * @param int $sessionId
     * @param string $vin
     */
    public static function init(int $sessionId, string $vin): self
    {
        return new self(new ChargingHistoryItem($sessionId, $vin));
    }

    /**
     * Sets site Location Name field.
     *
     * @param string|null $value
     */
    public function siteLocationName(?string $value): self
    {
        $this->instance->setSiteLocationName($value);
        return $this;
    }

    /**
     * Sets charge Start Date Time field.
     *
     * @param \DateTime|null $value
     */
    public function chargeStartDateTime(?\DateTime $value): self
    {
        $this->instance->setChargeStartDateTime($value);
        return $this;
    }

    /**
     * Sets charge Stop Date Time field.
     *
     * @param \DateTime|null $value
     */
    public function chargeStopDateTime(?\DateTime $value): self
    {
        $this->instance->setChargeStopDateTime($value);
        return $this;
    }

    /**
     * Sets unlatch Date Time field.
     *
     * @param \DateTime|null $value
     */
    public function unlatchDateTime(?\DateTime $value): self
    {
        $this->instance->setUnlatchDateTime($value);
        return $this;
    }

    /**
     * Sets country Code field.
     *
     * @param string|null $value
     */
    public function countryCode(?string $value): self
    {
        $this->instance->setCountryCode($value);
        return $this;
    }

    /**
     * Sets fees field.
     *
     * @param ChargingFee[]|null $value
     */
    public function fees(?array $value): self
    {
        $this->instance->setFees($value);
        return $this;
    }

    /**
     * Sets billing Type field.
     *
     * @param string|null $value
     */
    public function billingType(?string $value): self
    {
        $this->instance->setBillingType($value);
        return $this;
    }

    /**
     * Sets invoices field.
     *
     * @param ChargingInvoice[]|null $value
     */
    public function invoices(?array $value): self
    {
        $this->instance->setInvoices($value);
        return $this;
    }

    /**
     * Sets vehicle Make Type field.
     *
     * @param string|null $value
     */
    public function vehicleMakeType(?string $value): self
    {
        $this->instance->setVehicleMakeType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging History Item object.
     */
    public function build(): ChargingHistoryItem
    {
        return CoreHelper::clone($this->instance);
    }
}
