<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingPeriod;
use TeslaFleetManagementApiLib\Models\ChargingSession;
use TeslaFleetManagementApiLib\Models\Location;
use TeslaFleetManagementApiLib\Models\Tariffs;
use TeslaFleetManagementApiLib\Models\TotalCost;

/**
 * Builder for model ChargingSession
 *
 * @see ChargingSession
 */
class ChargingSessionBuilder
{
    /**
     * @var ChargingSession
     */
    private $instance;

    private function __construct(ChargingSession $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging Session Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargingSession());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets vin field.
     *
     * @param string|null $value
     */
    public function vin(?string $value): self
    {
        $this->instance->setVin($value);
        return $this;
    }

    /**
     * Sets model field.
     *
     * @param string|null $value
     */
    public function model(?string $value): self
    {
        $this->instance->setModel($value);
        return $this;
    }

    /**
     * Sets start date time field.
     *
     * @param string|null $value
     */
    public function startDateTime(?string $value): self
    {
        $this->instance->setStartDateTime($value);
        return $this;
    }

    /**
     * Sets stop date time field.
     *
     * @param string|null $value
     */
    public function stopDateTime(?string $value): self
    {
        $this->instance->setStopDateTime($value);
        return $this;
    }

    /**
     * Sets total energy field.
     *
     * @param float|null $value
     */
    public function totalEnergy(?float $value): self
    {
        $this->instance->setTotalEnergy($value);
        return $this;
    }

    /**
     * Sets total time field.
     *
     * @param float|null $value
     */
    public function totalTime(?float $value): self
    {
        $this->instance->setTotalTime($value);
        return $this;
    }

    /**
     * Sets total cost field.
     *
     * @param TotalCost|null $value
     */
    public function totalCost(?TotalCost $value): self
    {
        $this->instance->setTotalCost($value);
        return $this;
    }

    /**
     * Sets location field.
     *
     * @param Location|null $value
     */
    public function location(?Location $value): self
    {
        $this->instance->setLocation($value);
        return $this;
    }

    /**
     * Sets charging periods field.
     *
     * @param ChargingPeriod[]|null $value
     */
    public function chargingPeriods(?array $value): self
    {
        $this->instance->setChargingPeriods($value);
        return $this;
    }

    /**
     * Sets tariffs field.
     *
     * @param Tariffs|null $value
     */
    public function tariffs(?Tariffs $value): self
    {
        $this->instance->setTariffs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging Session object.
     */
    public function build(): ChargingSession
    {
        return CoreHelper::clone($this->instance);
    }
}
