<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargeDuration;

/**
 * Builder for model ChargeDuration
 *
 * @see ChargeDuration
 */
class ChargeDurationBuilder
{
    /**
     * @var ChargeDuration
     */
    private $instance;

    private function __construct(ChargeDuration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charge Duration Builder object.
     *
     * @param int $seconds
     */
    public static function init(int $seconds): self
    {
        return new self(new ChargeDuration($seconds));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charge Duration object.
     */
    public function build(): ChargeDuration
    {
        return CoreHelper::clone($this->instance);
    }
}
