<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingSessionsData;
use TeslaFleetManagementApiLib\Models\ChargingSessionsResponse;

/**
 * Builder for model ChargingSessionsResponse
 *
 * @see ChargingSessionsResponse
 */
class ChargingSessionsResponseBuilder
{
    /**
     * @var ChargingSessionsResponse
     */
    private $instance;

    private function __construct(ChargingSessionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging Sessions Response Builder object.
     *
     * @param ChargingSessionsData $response
     */
    public static function init(ChargingSessionsData $response): self
    {
        return new self(new ChargingSessionsResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging Sessions Response object.
     */
    public function build(): ChargingSessionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
