<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargeHistoryResponse;
use TeslaFleetManagementApiLib\Models\ResponseChargeHistoryResponse;

/**
 * Builder for model ChargeHistoryResponse
 *
 * @see ChargeHistoryResponse
 */
class ChargeHistoryResponseBuilder
{
    /**
     * @var ChargeHistoryResponse
     */
    private $instance;

    private function __construct(ChargeHistoryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charge History Response Builder object.
     *
     * @param ResponseChargeHistoryResponse $response
     */
    public static function init(ResponseChargeHistoryResponse $response): self
    {
        return new self(new ChargeHistoryResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charge History Response object.
     */
    public function build(): ChargeHistoryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
