<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargeDuration;
use TeslaFleetManagementApiLib\Models\ChargeHistory;
use TeslaFleetManagementApiLib\Models\ChargeStartTime;

/**
 * Builder for model ChargeHistory
 *
 * @see ChargeHistory
 */
class ChargeHistoryBuilder
{
    /**
     * @var ChargeHistory
     */
    private $instance;

    private function __construct(ChargeHistory $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charge History Builder object.
     *
     * @param ChargeStartTime $chargeStartTime
     * @param ChargeDuration $chargeDuration
     * @param int $energyAddedWh
     */
    public static function init(
        ChargeStartTime $chargeStartTime,
        ChargeDuration $chargeDuration,
        int $energyAddedWh
    ): self {
        return new self(new ChargeHistory($chargeStartTime, $chargeDuration, $energyAddedWh));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charge History object.
     */
    public function build(): ChargeHistory
    {
        return CoreHelper::clone($this->instance);
    }
}
