<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingSession;
use TeslaFleetManagementApiLib\Models\ChargingSessionsData;

/**
 * Builder for model ChargingSessionsData
 *
 * @see ChargingSessionsData
 */
class ChargingSessionsDataBuilder
{
    /**
     * @var ChargingSessionsData
     */
    private $instance;

    private function __construct(ChargingSessionsData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging Sessions Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargingSessionsData());
    }

    /**
     * Sets data field.
     *
     * @param ChargingSession[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets status code field.
     *
     * @param int|null $value
     */
    public function statusCode(?int $value): self
    {
        $this->instance->setStatusCode($value);
        return $this;
    }

    /**
     * Sets status message field.
     *
     * @param string|null $value
     */
    public function statusMessage(?string $value): self
    {
        $this->instance->setStatusMessage($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param array<string,string>|null $value
     */
    public function timestamp(?array $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging Sessions Data object.
     */
    public function build(): ChargingSessionsData
    {
        return CoreHelper::clone($this->instance);
    }
}
