<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingInvoice;

/**
 * Builder for model ChargingInvoice
 *
 * @see ChargingInvoice
 */
class ChargingInvoiceBuilder
{
    /**
     * @var ChargingInvoice
     */
    private $instance;

    private function __construct(ChargingInvoice $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging Invoice Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargingInvoice());
    }

    /**
     * Sets file Name field.
     *
     * @param string|null $value
     */
    public function fileName(?string $value): self
    {
        $this->instance->setFileName($value);
        return $this;
    }

    /**
     * Sets content Id field.
     *
     * @param string|null $value
     */
    public function contentId(?string $value): self
    {
        $this->instance->setContentId($value);
        return $this;
    }

    /**
     * Sets invoice Type field.
     *
     * @param string|null $value
     */
    public function invoiceType(?string $value): self
    {
        $this->instance->setInvoiceType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging Invoice object.
     */
    public function build(): ChargingInvoice
    {
        return CoreHelper::clone($this->instance);
    }
}
