<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingDimension;
use TeslaFleetManagementApiLib\Models\ChargingPeriod;

/**
 * Builder for model ChargingPeriod
 *
 * @see ChargingPeriod
 */
class ChargingPeriodBuilder
{
    /**
     * @var ChargingPeriod
     */
    private $instance;

    private function __construct(ChargingPeriod $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging Period Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargingPeriod());
    }

    /**
     * Sets start date time field.
     *
     * @param string|null $value
     */
    public function startDateTime(?string $value): self
    {
        $this->instance->setStartDateTime($value);
        return $this;
    }

    /**
     * Sets dimensions field.
     *
     * @param ChargingDimension[]|null $value
     */
    public function dimensions(?array $value): self
    {
        $this->instance->setDimensions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging Period object.
     */
    public function build(): ChargingPeriod
    {
        return CoreHelper::clone($this->instance);
    }
}
