<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingFee;

/**
 * Builder for model ChargingFee
 *
 * @see ChargingFee
 */
class ChargingFeeBuilder
{
    /**
     * @var ChargingFee
     */
    private $instance;

    private function __construct(ChargingFee $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging Fee Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargingFee());
    }

    /**
     * Sets session Fee Id field.
     *
     * @param int|null $value
     */
    public function sessionFeeId(?int $value): self
    {
        $this->instance->setSessionFeeId($value);
        return $this;
    }

    /**
     * Sets fee Type field.
     *
     * @param string|null $value
     */
    public function feeType(?string $value): self
    {
        $this->instance->setFeeType($value);
        return $this;
    }

    /**
     * Sets currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets pricing Type field.
     *
     * @param string|null $value
     */
    public function pricingType(?string $value): self
    {
        $this->instance->setPricingType($value);
        return $this;
    }

    /**
     * Sets rate Base field.
     *
     * @param float|null $value
     */
    public function rateBase(?float $value): self
    {
        $this->instance->setRateBase($value);
        return $this;
    }

    /**
     * Sets rate Tier 1 field.
     *
     * @param float|null $value
     */
    public function rateTier1(?float $value): self
    {
        $this->instance->setRateTier1($value);
        return $this;
    }

    /**
     * Sets rate Tier 2 field.
     *
     * @param float|null $value
     */
    public function rateTier2(?float $value): self
    {
        $this->instance->setRateTier2($value);
        return $this;
    }

    /**
     * Sets rate Tier 3 field.
     *
     * @param float|null $value
     */
    public function rateTier3(?float $value): self
    {
        $this->instance->setRateTier3($value);
        return $this;
    }

    /**
     * Unsets rate Tier 3 field.
     */
    public function unsetRateTier3(): self
    {
        $this->instance->unsetRateTier3();
        return $this;
    }

    /**
     * Sets rate Tier 4 field.
     *
     * @param float|null $value
     */
    public function rateTier4(?float $value): self
    {
        $this->instance->setRateTier4($value);
        return $this;
    }

    /**
     * Unsets rate Tier 4 field.
     */
    public function unsetRateTier4(): self
    {
        $this->instance->unsetRateTier4();
        return $this;
    }

    /**
     * Sets usage Base field.
     *
     * @param float|null $value
     */
    public function usageBase(?float $value): self
    {
        $this->instance->setUsageBase($value);
        return $this;
    }

    /**
     * Sets usage Tier 1 field.
     *
     * @param float|null $value
     */
    public function usageTier1(?float $value): self
    {
        $this->instance->setUsageTier1($value);
        return $this;
    }

    /**
     * Sets usage Tier 2 field.
     *
     * @param float|null $value
     */
    public function usageTier2(?float $value): self
    {
        $this->instance->setUsageTier2($value);
        return $this;
    }

    /**
     * Sets usage Tier 3 field.
     *
     * @param float|null $value
     */
    public function usageTier3(?float $value): self
    {
        $this->instance->setUsageTier3($value);
        return $this;
    }

    /**
     * Unsets usage Tier 3 field.
     */
    public function unsetUsageTier3(): self
    {
        $this->instance->unsetUsageTier3();
        return $this;
    }

    /**
     * Sets usage Tier 4 field.
     *
     * @param float|null $value
     */
    public function usageTier4(?float $value): self
    {
        $this->instance->setUsageTier4($value);
        return $this;
    }

    /**
     * Unsets usage Tier 4 field.
     */
    public function unsetUsageTier4(): self
    {
        $this->instance->unsetUsageTier4();
        return $this;
    }

    /**
     * Sets total Base field.
     *
     * @param float|null $value
     */
    public function totalBase(?float $value): self
    {
        $this->instance->setTotalBase($value);
        return $this;
    }

    /**
     * Sets total Tier 1 field.
     *
     * @param float|null $value
     */
    public function totalTier1(?float $value): self
    {
        $this->instance->setTotalTier1($value);
        return $this;
    }

    /**
     * Sets total Tier 2 field.
     *
     * @param float|null $value
     */
    public function totalTier2(?float $value): self
    {
        $this->instance->setTotalTier2($value);
        return $this;
    }

    /**
     * Sets total Tier 3 field.
     *
     * @param float|null $value
     */
    public function totalTier3(?float $value): self
    {
        $this->instance->setTotalTier3($value);
        return $this;
    }

    /**
     * Sets total Tier 4 field.
     *
     * @param float|null $value
     */
    public function totalTier4(?float $value): self
    {
        $this->instance->setTotalTier4($value);
        return $this;
    }

    /**
     * Sets total Due field.
     *
     * @param float|null $value
     */
    public function totalDue(?float $value): self
    {
        $this->instance->setTotalDue($value);
        return $this;
    }

    /**
     * Sets net Due field.
     *
     * @param float|null $value
     */
    public function netDue(?float $value): self
    {
        $this->instance->setNetDue($value);
        return $this;
    }

    /**
     * Sets uom field.
     *
     * @param string|null $value
     */
    public function uom(?string $value): self
    {
        $this->instance->setUom($value);
        return $this;
    }

    /**
     * Sets is Paid field.
     *
     * @param bool|null $value
     */
    public function isPaid(?bool $value): self
    {
        $this->instance->setIsPaid($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging Fee object.
     */
    public function build(): ChargingFee
    {
        return CoreHelper::clone($this->instance);
    }
}
