<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingHistoryData;
use TeslaFleetManagementApiLib\Models\ChargingHistoryItem;

/**
 * Builder for model ChargingHistoryData
 *
 * @see ChargingHistoryData
 */
class ChargingHistoryDataBuilder
{
    /**
     * @var ChargingHistoryData
     */
    private $instance;

    private function __construct(ChargingHistoryData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Charging History Data Builder object.
     *
     * @param ChargingHistoryItem[] $data
     */
    public static function init(array $data): self
    {
        return new self(new ChargingHistoryData($data));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Charging History Data object.
     */
    public function build(): ChargingHistoryData
    {
        return CoreHelper::clone($this->instance);
    }
}
