<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\CommandResult;

/**
 * Builder for model CommandResult
 *
 * @see CommandResult
 */
class CommandResultBuilder
{
    /**
     * @var CommandResult
     */
    private $instance;

    private function __construct(CommandResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Command Result Builder object.
     *
     * @param bool $result
     * @param string $reason
     */
    public static function init(bool $result, string $reason): self
    {
        return new self(new CommandResult($result, $reason));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Command Result object.
     */
    public function build(): CommandResult
    {
        return CoreHelper::clone($this->instance);
    }
}
