<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\CommandResponse;
use TeslaFleetManagementApiLib\Models\CommandResult;

/**
 * Builder for model CommandResponse
 *
 * @see CommandResponse
 */
class CommandResponseBuilder
{
    /**
     * @var CommandResponse
     */
    private $instance;

    private function __construct(CommandResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Command Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CommandResponse());
    }

    /**
     * Sets response field.
     *
     * @param CommandResult|null $value
     */
    public function response(?CommandResult $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Command Response object.
     */
    public function build(): CommandResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
