<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Driver;
use TeslaFleetManagementApiLib\Models\DriversResponse;

/**
 * Builder for model DriversResponse
 *
 * @see DriversResponse
 */
class DriversResponseBuilder
{
    /**
     * @var DriversResponse
     */
    private $instance;

    private function __construct(DriversResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Drivers Response Builder object.
     */
    public static function init(): self
    {
        return new self(new DriversResponse());
    }

    /**
     * Sets response field.
     *
     * @param Driver[]|null $value
     */
    public function response(?array $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Drivers Response object.
     */
    public function build(): DriversResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
