<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\EnterprisePayerRequest;

/**
 * Builder for model EnterprisePayerRequest
 *
 * @see EnterprisePayerRequest
 */
class EnterprisePayerRequestBuilder
{
    /**
     * @var EnterprisePayerRequest
     */
    private $instance;

    private function __construct(EnterprisePayerRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Enterprise Payer Request Builder object.
     *
     * @param string $role
     */
    public static function init(string $role): self
    {
        return new self(new EnterprisePayerRequest($role));
    }

    /**
     * Sets federation id field.
     *
     * @param string|null $value
     */
    public function federationId(?string $value): self
    {
        $this->instance->setFederationId($value);
        return $this;
    }

    /**
     * Sets account id field.
     *
     * @param string|null $value
     */
    public function accountId(?string $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Enterprise Payer Request object.
     */
    public function build(): EnterprisePayerRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
