<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\FleetTelemetryJwsRequest;

/**
 * Builder for model FleetTelemetryJwsRequest
 *
 * @see FleetTelemetryJwsRequest
 */
class FleetTelemetryJwsRequestBuilder
{
    /**
     * @var FleetTelemetryJwsRequest
     */
    private $instance;

    private function __construct(FleetTelemetryJwsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fleet Telemetry Jws Request Builder object.
     */
    public static function init(): self
    {
        return new self(new FleetTelemetryJwsRequest());
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets vins field.
     *
     * @param string[]|null $value
     */
    public function vins(?array $value): self
    {
        $this->instance->setVins($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Fleet Telemetry Jws Request object.
     */
    public function build(): FleetTelemetryJwsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
