<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\FleetTelemetryErrorsResponse;
use TeslaFleetManagementApiLib\Models\ResponseFleetTelemetryErrorsResponse;

/**
 * Builder for model FleetTelemetryErrorsResponse
 *
 * @see FleetTelemetryErrorsResponse
 */
class FleetTelemetryErrorsResponseBuilder
{
    /**
     * @var FleetTelemetryErrorsResponse
     */
    private $instance;

    private function __construct(FleetTelemetryErrorsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fleet Telemetry Errors Response Builder object.
     *
     * @param ResponseFleetTelemetryErrorsResponse $response
     */
    public static function init(ResponseFleetTelemetryErrorsResponse $response): self
    {
        return new self(new FleetTelemetryErrorsResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Fleet Telemetry Errors Response object.
     */
    public function build(): FleetTelemetryErrorsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
