<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\FleetTelemetryError;

/**
 * Builder for model FleetTelemetryError
 *
 * @see FleetTelemetryError
 */
class FleetTelemetryErrorBuilder
{
    /**
     * @var FleetTelemetryError
     */
    private $instance;

    private function __construct(FleetTelemetryError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fleet Telemetry Error Builder object.
     *
     * @param string $name
     * @param string $error
     * @param string $vin
     */
    public static function init(string $name, string $error, string $vin): self
    {
        return new self(new FleetTelemetryError($name, $error, $vin));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Fleet Telemetry Error object.
     */
    public function build(): FleetTelemetryError
    {
        return CoreHelper::clone($this->instance);
    }
}
