<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\GuestModeRequest;

/**
 * Builder for model GuestModeRequest
 *
 * @see GuestModeRequest
 */
class GuestModeRequestBuilder
{
    /**
     * @var GuestModeRequest
     */
    private $instance;

    private function __construct(GuestModeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Guest Mode Request Builder object.
     *
     * @param bool $enable
     */
    public static function init(bool $enable): self
    {
        return new self(new GuestModeRequest($enable));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Guest Mode Request object.
     */
    public function build(): GuestModeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
