<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\LiveStatusResponse;
use TeslaFleetManagementApiLib\Models\ResponseLiveStatusResponse;

/**
 * Builder for model LiveStatusResponse
 *
 * @see LiveStatusResponse
 */
class LiveStatusResponseBuilder
{
    /**
     * @var LiveStatusResponse
     */
    private $instance;

    private function __construct(LiveStatusResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Live Status Response Builder object.
     *
     * @param ResponseLiveStatusResponse $response
     */
    public static function init(ResponseLiveStatusResponse $response): self
    {
        return new self(new LiveStatusResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Live Status Response object.
     */
    public function build(): LiveStatusResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
