<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Location1;

/**
 * Builder for model Location1
 *
 * @see Location1
 */
class Location1Builder
{
    /**
     * @var Location1
     */
    private $instance;

    private function __construct(Location1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Location 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Location1());
    }

    /**
     * Sets lat field.
     *
     * @param float|null $value
     */
    public function lat(?float $value): self
    {
        $this->instance->setLat($value);
        return $this;
    }

    /**
     * Sets long field.
     *
     * @param float|null $value
     */
    public function long(?float $value): self
    {
        $this->instance->setLong($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Location 1 object.
     */
    public function build(): Location1
    {
        return CoreHelper::clone($this->instance);
    }
}
