<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\MeResponse;
use TeslaFleetManagementApiLib\Models\ResponseMeResponse;

/**
 * Builder for model MeResponse
 *
 * @see MeResponse
 */
class MeResponseBuilder
{
    /**
     * @var MeResponse
     */
    private $instance;

    private function __construct(MeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Me Response Builder object.
     *
     * @param ResponseMeResponse $response
     */
    public static function init(ResponseMeResponse $response): self
    {
        return new self(new MeResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Me Response object.
     */
    public function build(): MeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
