<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\MobileEnabled;

/**
 * Builder for model MobileEnabled
 *
 * @see MobileEnabled
 */
class MobileEnabledBuilder
{
    /**
     * @var MobileEnabled
     */
    private $instance;

    private function __construct(MobileEnabled $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Mobile Enabled Builder object.
     */
    public static function init(): self
    {
        return new self(new MobileEnabled());
    }

    /**
     * Sets result field.
     *
     * @param bool|null $value
     */
    public function result(?bool $value): self
    {
        $this->instance->setResult($value);
        return $this;
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Mobile Enabled object.
     */
    public function build(): MobileEnabled
    {
        return CoreHelper::clone($this->instance);
    }
}
