<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\OffGridVehicleChargingReserveRequest;

/**
 * Builder for model OffGridVehicleChargingReserveRequest
 *
 * @see OffGridVehicleChargingReserveRequest
 */
class OffGridVehicleChargingReserveRequestBuilder
{
    /**
     * @var OffGridVehicleChargingReserveRequest
     */
    private $instance;

    private function __construct(OffGridVehicleChargingReserveRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Off Grid Vehicle Charging Reserve Request Builder object.
     *
     * @param int $offGridVehicleChargingReservePercent
     */
    public static function init(int $offGridVehicleChargingReservePercent): self
    {
        return new self(new OffGridVehicleChargingReserveRequest($offGridVehicleChargingReservePercent));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Off Grid Vehicle Charging Reserve Request object.
     */
    public function build(): OffGridVehicleChargingReserveRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
