<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\OrdersResponse;
use TeslaFleetManagementApiLib\Models\ResponseOrdersResponse;

/**
 * Builder for model OrdersResponse
 *
 * @see OrdersResponse
 */
class OrdersResponseBuilder
{
    /**
     * @var OrdersResponse
     */
    private $instance;

    private function __construct(OrdersResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Orders Response Builder object.
     *
     * @param ResponseOrdersResponse[] $response
     * @param int $count
     */
    public static function init(array $response, int $count): self
    {
        return new self(new OrdersResponse($response, $count));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Orders Response object.
     */
    public function build(): OrdersResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
