<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Pagination;

/**
 * Builder for model Pagination
 *
 * @see Pagination
 */
class PaginationBuilder
{
    /**
     * @var Pagination
     */
    private $instance;

    private function __construct(Pagination $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pagination Builder object.
     */
    public static function init(): self
    {
        return new self(new Pagination());
    }

    /**
     * Sets previous field.
     *
     * @param int|null $value
     */
    public function previous(?int $value): self
    {
        $this->instance->setPrevious($value);
        return $this;
    }

    /**
     * Unsets previous field.
     */
    public function unsetPrevious(): self
    {
        $this->instance->unsetPrevious();
        return $this;
    }

    /**
     * Sets next field.
     *
     * @param int|null $value
     */
    public function next(?int $value): self
    {
        $this->instance->setNext($value);
        return $this;
    }

    /**
     * Unsets next field.
     */
    public function unsetNext(): self
    {
        $this->instance->unsetNext();
        return $this;
    }

    /**
     * Sets current field.
     *
     * @param int|null $value
     */
    public function current(?int $value): self
    {
        $this->instance->setCurrent($value);
        return $this;
    }

    /**
     * Sets per page field.
     *
     * @param int|null $value
     */
    public function perPage(?int $value): self
    {
        $this->instance->setPerPage($value);
        return $this;
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Sets pages field.
     *
     * @param int|null $value
     */
    public function pages(?int $value): self
    {
        $this->instance->setPages($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Pagination object.
     */
    public function build(): Pagination
    {
        return CoreHelper::clone($this->instance);
    }
}
