<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\PriceComponent;

/**
 * Builder for model PriceComponent
 *
 * @see PriceComponent
 */
class PriceComponentBuilder
{
    /**
     * @var PriceComponent
     */
    private $instance;

    private function __construct(PriceComponent $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Price Component Builder object.
     */
    public static function init(): self
    {
        return new self(new PriceComponent());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param float|null $value
     */
    public function price(?float $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Sets step size field.
     *
     * @param float|null $value
     */
    public function stepSize(?float $value): self
    {
        $this->instance->setStepSize($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Price Component object.
     */
    public function build(): PriceComponent
    {
        return CoreHelper::clone($this->instance);
    }
}
