<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ProductsResponse;

/**
 * Builder for model ProductsResponse
 *
 * @see ProductsResponse
 */
class ProductsResponseBuilder
{
    /**
     * @var ProductsResponse
     */
    private $instance;

    private function __construct(ProductsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Products Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ProductsResponse());
    }

    /**
     * Sets response field.
     *
     * @param array[]|null $value
     */
    public function response(?array $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Products Response object.
     */
    public function build(): ProductsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
