<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\PublicKeyResponse;
use TeslaFleetManagementApiLib\Models\ResponsePublicKeyResponse;

/**
 * Builder for model PublicKeyResponse
 *
 * @see PublicKeyResponse
 */
class PublicKeyResponseBuilder
{
    /**
     * @var PublicKeyResponse
     */
    private $instance;

    private function __construct(PublicKeyResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Public Key Response Builder object.
     *
     * @param ResponsePublicKeyResponse $response
     */
    public static function init(ResponsePublicKeyResponse $response): self
    {
        return new self(new PublicKeyResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Public Key Response object.
     */
    public function build(): PublicKeyResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
