<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\RegisterPartnerResponse;
use TeslaFleetManagementApiLib\Models\ResponseRegisterPartnerResponse;

/**
 * Builder for model RegisterPartnerResponse
 *
 * @see RegisterPartnerResponse
 */
class RegisterPartnerResponseBuilder
{
    /**
     * @var RegisterPartnerResponse
     */
    private $instance;

    private function __construct(RegisterPartnerResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Register Partner Response Builder object.
     *
     * @param ResponseRegisterPartnerResponse $response
     */
    public static function init(ResponseRegisterPartnerResponse $response): self
    {
        return new self(new RegisterPartnerResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Register Partner Response object.
     */
    public function build(): RegisterPartnerResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
