<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\RegionResponse;
use TeslaFleetManagementApiLib\Models\ResponseRegionResponse;

/**
 * Builder for model RegionResponse
 *
 * @see RegionResponse
 */
class RegionResponseBuilder
{
    /**
     * @var RegionResponse
     */
    private $instance;

    private function __construct(RegionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Region Response Builder object.
     *
     * @param ResponseRegionResponse $response
     */
    public static function init(ResponseRegionResponse $response): self
    {
        return new self(new RegionResponse($response));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Region Response object.
     */
    public function build(): RegionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
