<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\RegisterPartnerRequest;

/**
 * Builder for model RegisterPartnerRequest
 *
 * @see RegisterPartnerRequest
 */
class RegisterPartnerRequestBuilder
{
    /**
     * @var RegisterPartnerRequest
     */
    private $instance;

    private function __construct(RegisterPartnerRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Register Partner Request Builder object.
     *
     * @param string $domain
     */
    public static function init(string $domain): self
    {
        return new self(new RegisterPartnerRequest($domain));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Register Partner Request object.
     */
    public function build(): RegisterPartnerRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
