<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponseOrdersResponse;

/**
 * Builder for model ResponseOrdersResponse
 *
 * @see ResponseOrdersResponse
 */
class ResponseOrdersResponseBuilder
{
    /**
     * @var ResponseOrdersResponse
     */
    private $instance;

    private function __construct(ResponseOrdersResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Orders Response Builder object.
     *
     * @param int $vehicleMapId
     * @param string $referenceNumber
     * @param string $vin
     * @param string $orderStatus
     * @param string $orderSubstatus
     * @param string $modelCode
     * @param string $countryCode
     * @param string $locale
     * @param string $mktOptions
     * @param bool $isB2B
     */
    public static function init(
        int $vehicleMapId,
        string $referenceNumber,
        string $vin,
        string $orderStatus,
        string $orderSubstatus,
        string $modelCode,
        string $countryCode,
        string $locale,
        string $mktOptions,
        bool $isB2B
    ): self {
        return new self(new ResponseOrdersResponse(
            $vehicleMapId,
            $referenceNumber,
            $vin,
            $orderStatus,
            $orderSubstatus,
            $modelCode,
            $countryCode,
            $locale,
            $mktOptions,
            $isB2B
        ));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Orders Response object.
     */
    public function build(): ResponseOrdersResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
