<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponsePublicKeyResponse;

/**
 * Builder for model ResponsePublicKeyResponse
 *
 * @see ResponsePublicKeyResponse
 */
class ResponsePublicKeyResponseBuilder
{
    /**
     * @var ResponsePublicKeyResponse
     */
    private $instance;

    private function __construct(ResponsePublicKeyResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Public Key Response Builder object.
     *
     * @param string $publicKey
     */
    public static function init(string $publicKey): self
    {
        return new self(new ResponsePublicKeyResponse($publicKey));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Public Key Response object.
     */
    public function build(): ResponsePublicKeyResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
