<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Response2;
use TeslaFleetManagementApiLib\Models\Signaling;

/**
 * Builder for model Response2
 *
 * @see Response2
 */
class Response2Builder
{
    /**
     * @var Response2
     */
    private $instance;

    private function __construct(Response2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response 2 Builder object.
     *
     * @param Signaling $signaling
     */
    public static function init(Signaling $signaling): self
    {
        return new self(new Response2($signaling));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response 2 object.
     */
    public function build(): Response2
    {
        return CoreHelper::clone($this->instance);
    }
}
