<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponseRegionResponse;

/**
 * Builder for model ResponseRegionResponse
 *
 * @see ResponseRegionResponse
 */
class ResponseRegionResponseBuilder
{
    /**
     * @var ResponseRegionResponse
     */
    private $instance;

    private function __construct(ResponseRegionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Region Response Builder object.
     *
     * @param string $region
     * @param string $fleetApiBaseUrl
     */
    public static function init(string $region, string $fleetApiBaseUrl): self
    {
        return new self(new ResponseRegionResponse($region, $fleetApiBaseUrl));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Region Response object.
     */
    public function build(): ResponseRegionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
