<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Response;

/**
 * Builder for model Response
 *
 * @see Response
 */
class ResponseBuilder
{
    /**
     * @var Response
     */
    private $instance;

    private function __construct(Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Builder object.
     *
     * @param int $code
     * @param string $message
     */
    public static function init(int $code, string $message): self
    {
        return new self(new Response($code, $message));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response object.
     */
    public function build(): Response
    {
        return CoreHelper::clone($this->instance);
    }
}
