<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargingLocation;
use TeslaFleetManagementApiLib\Models\Response3;

/**
 * Builder for model Response3
 *
 * @see Response3
 */
class Response3Builder
{
    /**
     * @var Response3
     */
    private $instance;

    private function __construct(Response3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response 3 Builder object.
     */
    public static function init(): self
    {
        return new self(new Response3());
    }

    /**
     * Sets destination charging field.
     *
     * @param ChargingLocation[]|null $value
     */
    public function destinationCharging(?array $value): self
    {
        $this->instance->setDestinationCharging($value);
        return $this;
    }

    /**
     * Sets superchargers field.
     *
     * @param ChargingLocation[]|null $value
     */
    public function superchargers(?array $value): self
    {
        $this->instance->setSuperchargers($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param int|null $value
     */
    public function timestamp(?int $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response 3 object.
     */
    public function build(): Response3
    {
        return CoreHelper::clone($this->instance);
    }
}
