<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponseLiveStatusResponse;

/**
 * Builder for model ResponseLiveStatusResponse
 *
 * @see ResponseLiveStatusResponse
 */
class ResponseLiveStatusResponseBuilder
{
    /**
     * @var ResponseLiveStatusResponse
     */
    private $instance;

    private function __construct(ResponseLiveStatusResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Live Status Response Builder object.
     *
     * @param float $solarPower
     * @param float $energyLeft
     * @param float $totalPackEnergy
     * @param float $percentageCharged
     * @param bool $backupCapable
     */
    public static function init(
        float $solarPower,
        float $energyLeft,
        float $totalPackEnergy,
        float $percentageCharged,
        bool $backupCapable
    ): self {
        return new self(new ResponseLiveStatusResponse(
            $solarPower,
            $energyLeft,
            $totalPackEnergy,
            $percentageCharged,
            $backupCapable
        ));
    }

    /**
     * Sets battery power field.
     *
     * @param float|null $value
     */
    public function batteryPower(?float $value): self
    {
        $this->instance->setBatteryPower($value);
        return $this;
    }

    /**
     * Sets load power field.
     *
     * @param float|null $value
     */
    public function loadPower(?float $value): self
    {
        $this->instance->setLoadPower($value);
        return $this;
    }

    /**
     * Sets grid status field.
     *
     * @param string|null $value
     */
    public function gridStatus(?string $value): self
    {
        $this->instance->setGridStatus($value);
        return $this;
    }

    /**
     * Sets grid power field.
     *
     * @param float|null $value
     */
    public function gridPower(?float $value): self
    {
        $this->instance->setGridPower($value);
        return $this;
    }

    /**
     * Sets island status field.
     *
     * @param string|null $value
     */
    public function islandStatus(?string $value): self
    {
        $this->instance->setIslandStatus($value);
        return $this;
    }

    /**
     * Sets storm mode active field.
     *
     * @param bool|null $value
     */
    public function stormModeActive(?bool $value): self
    {
        $this->instance->setStormModeActive($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param \DateTime|null $value
     */
    public function timestamp(?\DateTime $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Live Status Response object.
     */
    public function build(): ResponseLiveStatusResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
