<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Event;
use TeslaFleetManagementApiLib\Models\ResponseCalendarHistoryResponse;

/**
 * Builder for model ResponseCalendarHistoryResponse
 *
 * @see ResponseCalendarHistoryResponse
 */
class ResponseCalendarHistoryResponseBuilder
{
    /**
     * @var ResponseCalendarHistoryResponse
     */
    private $instance;

    private function __construct(ResponseCalendarHistoryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Calendar History Response Builder object.
     *
     * @param Event[] $events
     * @param int $totalEvents
     */
    public static function init(array $events, int $totalEvents): self
    {
        return new self(new ResponseCalendarHistoryResponse($events, $totalEvents));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Calendar History Response object.
     */
    public function build(): ResponseCalendarHistoryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
