<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ChargeHistory;
use TeslaFleetManagementApiLib\Models\ResponseChargeHistoryResponse;

/**
 * Builder for model ResponseChargeHistoryResponse
 *
 * @see ResponseChargeHistoryResponse
 */
class ResponseChargeHistoryResponseBuilder
{
    /**
     * @var ResponseChargeHistoryResponse
     */
    private $instance;

    private function __construct(ResponseChargeHistoryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Charge History Response Builder object.
     *
     * @param ChargeHistory[] $chargeHistory
     */
    public static function init(array $chargeHistory): self
    {
        return new self(new ResponseChargeHistoryResponse($chargeHistory));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Charge History Response object.
     */
    public function build(): ResponseChargeHistoryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
