<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\FleetTelemetryError;
use TeslaFleetManagementApiLib\Models\ResponseFleetTelemetryErrorsResponse;

/**
 * Builder for model ResponseFleetTelemetryErrorsResponse
 *
 * @see ResponseFleetTelemetryErrorsResponse
 */
class ResponseFleetTelemetryErrorsResponseBuilder
{
    /**
     * @var ResponseFleetTelemetryErrorsResponse
     */
    private $instance;

    private function __construct(ResponseFleetTelemetryErrorsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Fleet Telemetry Errors Response Builder object.
     *
     * @param FleetTelemetryError[] $fleetTelemetryErrors
     */
    public static function init(array $fleetTelemetryErrors): self
    {
        return new self(new ResponseFleetTelemetryErrorsResponse($fleetTelemetryErrors));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Fleet Telemetry Errors Response object.
     */
    public function build(): ResponseFleetTelemetryErrorsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
