<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponseMeResponse;

/**
 * Builder for model ResponseMeResponse
 *
 * @see ResponseMeResponse
 */
class ResponseMeResponseBuilder
{
    /**
     * @var ResponseMeResponse
     */
    private $instance;

    private function __construct(ResponseMeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Me Response Builder object.
     *
     * @param string $email
     * @param string $fullName
     * @param string $profileImageUrl
     * @param string $vaultUuid
     */
    public static function init(string $email, string $fullName, string $profileImageUrl, string $vaultUuid): self
    {
        return new self(new ResponseMeResponse($email, $fullName, $profileImageUrl, $vaultUuid));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Me Response object.
     */
    public function build(): ResponseMeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
