<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponseApi1DxVehiclesOptionsResponse;
use TeslaFleetManagementApiLib\Models\VehicleOption;

/**
 * Builder for model ResponseApi1DxVehiclesOptionsResponse
 *
 * @see ResponseApi1DxVehiclesOptionsResponse
 */
class ResponseApi1DxVehiclesOptionsResponseBuilder
{
    /**
     * @var ResponseApi1DxVehiclesOptionsResponse
     */
    private $instance;

    private function __construct(ResponseApi1DxVehiclesOptionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Api 1 Dx Vehicles Options Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseApi1DxVehiclesOptionsResponse());
    }

    /**
     * Sets codes field.
     *
     * @param VehicleOption[]|null $value
     */
    public function codes(?array $value): self
    {
        $this->instance->setCodes($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Api 1 Dx Vehicles Options Response object.
     */
    public function build(): ResponseApi1DxVehiclesOptionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
