<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\ResponseApi1DxWarrantyDetailsResponse;
use TeslaFleetManagementApiLib\Models\WarrantyItem;

/**
 * Builder for model ResponseApi1DxWarrantyDetailsResponse
 *
 * @see ResponseApi1DxWarrantyDetailsResponse
 */
class ResponseApi1DxWarrantyDetailsResponseBuilder
{
    /**
     * @var ResponseApi1DxWarrantyDetailsResponse
     */
    private $instance;

    private function __construct(ResponseApi1DxWarrantyDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response Api 1 Dx Warranty Details Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseApi1DxWarrantyDetailsResponse());
    }

    /**
     * Sets active Warranty field.
     *
     * @param WarrantyItem[]|null $value
     */
    public function activeWarranty(?array $value): self
    {
        $this->instance->setActiveWarranty($value);
        return $this;
    }

    /**
     * Sets upcoming Warranty field.
     *
     * @param WarrantyItem[]|null $value
     */
    public function upcomingWarranty(?array $value): self
    {
        $this->instance->setUpcomingWarranty($value);
        return $this;
    }

    /**
     * Sets expired Warranty field.
     *
     * @param WarrantyItem[]|null $value
     */
    public function expiredWarranty(?array $value): self
    {
        $this->instance->setExpiredWarranty($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response Api 1 Dx Warranty Details Response object.
     */
    public function build(): ResponseApi1DxWarrantyDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
