<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\Response1;

/**
 * Builder for model Response1
 *
 * @see Response1
 */
class Response1Builder
{
    /**
     * @var Response1
     */
    private $instance;

    private function __construct(Response1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Response 1 Builder object.
     *
     * @param string[] $fleetTelemetryErrorVins
     */
    public static function init(array $fleetTelemetryErrorVins): self
    {
        return new self(new Response1($fleetTelemetryErrorVins));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Response 1 object.
     */
    public function build(): Response1
    {
        return CoreHelper::clone($this->instance);
    }
}
