<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\SimpleOkResponse;

/**
 * Builder for model SimpleOkResponse
 *
 * @see SimpleOkResponse
 */
class SimpleOkResponseBuilder
{
    /**
     * @var SimpleOkResponse
     */
    private $instance;

    private function __construct(SimpleOkResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Simple Ok Response Builder object.
     */
    public static function init(): self
    {
        return new self(new SimpleOkResponse());
    }

    /**
     * Sets response field.
     *
     * @param string|null $value
     */
    public function response(?string $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Simple Ok Response object.
     */
    public function build(): SimpleOkResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
