<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\SiteInfoResponse;

/**
 * Builder for model SiteInfoResponse
 *
 * @see SiteInfoResponse
 */
class SiteInfoResponseBuilder
{
    /**
     * @var SiteInfoResponse
     */
    private $instance;

    private function __construct(SiteInfoResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Site Info Response Builder object.
     */
    public static function init(): self
    {
        return new self(new SiteInfoResponse());
    }

    /**
     * Sets response field.
     *
     * @param array|null $value
     */
    public function response(?array $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Site Info Response object.
     */
    public function build(): SiteInfoResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
