<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\StormModeRequest;

/**
 * Builder for model StormModeRequest
 *
 * @see StormModeRequest
 */
class StormModeRequestBuilder
{
    /**
     * @var StormModeRequest
     */
    private $instance;

    private function __construct(StormModeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Storm Mode Request Builder object.
     *
     * @param bool $enabled
     */
    public static function init(bool $enabled): self
    {
        return new self(new StormModeRequest($enabled));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Storm Mode Request object.
     */
    public function build(): StormModeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
