<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\TariffElement;
use TeslaFleetManagementApiLib\Models\Tariffs;

/**
 * Builder for model Tariffs
 *
 * @see Tariffs
 */
class TariffsBuilder
{
    /**
     * @var Tariffs
     */
    private $instance;

    private function __construct(Tariffs $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tariffs Builder object.
     */
    public static function init(): self
    {
        return new self(new Tariffs());
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets elements field.
     *
     * @param TariffElement[]|null $value
     */
    public function elements(?array $value): self
    {
        $this->instance->setElements($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Tariffs object.
     */
    public function build(): Tariffs
    {
        return CoreHelper::clone($this->instance);
    }
}
