<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\PriceComponent;
use TeslaFleetManagementApiLib\Models\TariffElement;

/**
 * Builder for model TariffElement
 *
 * @see TariffElement
 */
class TariffElementBuilder
{
    /**
     * @var TariffElement
     */
    private $instance;

    private function __construct(TariffElement $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tariff Element Builder object.
     */
    public static function init(): self
    {
        return new self(new TariffElement());
    }

    /**
     * Sets price components field.
     *
     * @param PriceComponent[]|null $value
     */
    public function priceComponents(?array $value): self
    {
        $this->instance->setPriceComponents($value);
        return $this;
    }

    /**
     * Sets restrictions field.
     *
     * @param array|null $value
     */
    public function restrictions(?array $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Tariff Element object.
     */
    public function build(): TariffElement
    {
        return CoreHelper::clone($this->instance);
    }
}
