<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\TotalCost;

/**
 * Builder for model TotalCost
 *
 * @see TotalCost
 */
class TotalCostBuilder
{
    /**
     * @var TotalCost
     */
    private $instance;

    private function __construct(TotalCost $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Total Cost Builder object.
     */
    public static function init(): self
    {
        return new self(new TotalCost());
    }

    /**
     * Sets excl vat field.
     *
     * @param float|null $value
     */
    public function exclVat(?float $value): self
    {
        $this->instance->setExclVat($value);
        return $this;
    }

    /**
     * Sets incl vat field.
     *
     * @param float|null $value
     */
    public function inclVat(?float $value): self
    {
        $this->instance->setInclVat($value);
        return $this;
    }

    /**
     * Sets vat field.
     *
     * @param float|null $value
     */
    public function vat(?float $value): self
    {
        $this->instance->setVat($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Total Cost object.
     */
    public function build(): TotalCost
    {
        return CoreHelper::clone($this->instance);
    }
}
