<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\TouSettings;

/**
 * Builder for model TouSettings
 *
 * @see TouSettings
 */
class TouSettingsBuilder
{
    /**
     * @var TouSettings
     */
    private $instance;

    private function __construct(TouSettings $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tou Settings Builder object.
     */
    public static function init(): self
    {
        return new self(new TouSettings());
    }

    /**
     * Sets tariff content v 2 field.
     *
     * @param array|null $value
     */
    public function tariffContentV2(?array $value): self
    {
        $this->instance->setTariffContentV2($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Tou Settings object.
     */
    public function build(): TouSettings
    {
        return CoreHelper::clone($this->instance);
    }
}
