<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\VehicleOption;

/**
 * Builder for model VehicleOption
 *
 * @see VehicleOption
 */
class VehicleOptionBuilder
{
    /**
     * @var VehicleOption
     */
    private $instance;

    private function __construct(VehicleOption $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vehicle Option Builder object.
     */
    public static function init(): self
    {
        return new self(new VehicleOption());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets display Name field.
     *
     * @param string|null $value
     */
    public function displayName(?string $value): self
    {
        $this->instance->setDisplayName($value);
        return $this;
    }

    /**
     * Sets color Code field.
     *
     * @param string|null $value
     */
    public function colorCode(?string $value): self
    {
        $this->instance->setColorCode($value);
        return $this;
    }

    /**
     * Unsets color Code field.
     */
    public function unsetColorCode(): self
    {
        $this->instance->unsetColorCode();
        return $this;
    }

    /**
     * Sets is Active field.
     *
     * @param bool|null $value
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Vehicle Option object.
     */
    public function build(): VehicleOption
    {
        return CoreHelper::clone($this->instance);
    }
}
