<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\VehicleBase;

/**
 * Builder for model VehicleBase
 *
 * @see VehicleBase
 */
class VehicleBaseBuilder
{
    /**
     * @var VehicleBase
     */
    private $instance;

    private function __construct(VehicleBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vehicle Base Builder object.
     */
    public static function init(): self
    {
        return new self(new VehicleBase());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets vehicle id field.
     *
     * @param int|null $value
     */
    public function vehicleId(?int $value): self
    {
        $this->instance->setVehicleId($value);
        return $this;
    }

    /**
     * Sets vin field.
     *
     * @param string|null $value
     */
    public function vin(?string $value): self
    {
        $this->instance->setVin($value);
        return $this;
    }

    /**
     * Sets display name field.
     *
     * @param string|null $value
     */
    public function displayName(?string $value): self
    {
        $this->instance->setDisplayName($value);
        return $this;
    }

    /**
     * Sets access type field.
     *
     * @param string|null $value
     */
    public function accessType(?string $value): self
    {
        $this->instance->setAccessType($value);
        return $this;
    }

    /**
     * Sets state field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets in service field.
     *
     * @param bool|null $value
     */
    public function inService(?bool $value): self
    {
        $this->instance->setInService($value);
        return $this;
    }

    /**
     * Sets calendar enabled field.
     *
     * @param bool|null $value
     */
    public function calendarEnabled(?bool $value): self
    {
        $this->instance->setCalendarEnabled($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Vehicle Base object.
     */
    public function build(): VehicleBase
    {
        return CoreHelper::clone($this->instance);
    }
}
