<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use TeslaFleetManagementApiLib\Models\WarrantyItem;

/**
 * Builder for model WarrantyItem
 *
 * @see WarrantyItem
 */
class WarrantyItemBuilder
{
    /**
     * @var WarrantyItem
     */
    private $instance;

    private function __construct(WarrantyItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Warranty Item Builder object.
     */
    public static function init(): self
    {
        return new self(new WarrantyItem());
    }

    /**
     * Sets warranty Type field.
     *
     * @param string|null $value
     */
    public function warrantyType(?string $value): self
    {
        $this->instance->setWarrantyType($value);
        return $this;
    }

    /**
     * Sets warranty Display Name field.
     *
     * @param string|null $value
     */
    public function warrantyDisplayName(?string $value): self
    {
        $this->instance->setWarrantyDisplayName($value);
        return $this;
    }

    /**
     * Sets expiration Date field.
     *
     * @param \DateTime|null $value
     */
    public function expirationDate(?\DateTime $value): self
    {
        $this->instance->setExpirationDate($value);
        return $this;
    }

    /**
     * Sets expiration Odometer field.
     *
     * @param int|null $value
     */
    public function expirationOdometer(?int $value): self
    {
        $this->instance->setExpirationOdometer($value);
        return $this;
    }

    /**
     * Sets odometer Unit field.
     *
     * @param string|null $value
     */
    public function odometerUnit(?string $value): self
    {
        $this->instance->setOdometerUnit($value);
        return $this;
    }

    /**
     * Sets warranty Expired On field.
     *
     * @param string|null $value
     */
    public function warrantyExpiredOn(?string $value): self
    {
        $this->instance->setWarrantyExpiredOn($value);
        return $this;
    }

    /**
     * Unsets warranty Expired On field.
     */
    public function unsetWarrantyExpiredOn(): self
    {
        $this->instance->unsetWarrantyExpiredOn();
        return $this;
    }

    /**
     * Sets coverage Age In Years field.
     *
     * @param int|null $value
     */
    public function coverageAgeInYears(?int $value): self
    {
        $this->instance->setCoverageAgeInYears($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Warranty Item object.
     */
    public function build(): WarrantyItem
    {
        return CoreHelper::clone($this->instance);
    }
}
