<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\TemplateParam;
use CoreInterfaces\Core\Request\RequestMethod;
use TeslaFleetManagementApiLib\Http\ApiResponse;
use TeslaFleetManagementApiLib\Models\ActuateTrunkRequest;
use TeslaFleetManagementApiLib\Models\AddChargeScheduleRequest;
use TeslaFleetManagementApiLib\Models\AddPreconditionScheduleRequest;
use TeslaFleetManagementApiLib\Models\AdjustVolumeRequest;
use TeslaFleetManagementApiLib\Models\CommandResponse;
use TeslaFleetManagementApiLib\Models\GuestModeRequest;

class VehicleCommandsController extends BaseController
{
    /**
     * Controls the front or rear trunk
     *
     * @param string $vehicleTag
     * @param ActuateTrunkRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function actuateTrunk(string $vehicleTag, ActuateTrunkRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/actuate_trunk'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(
                TemplateParam::init('vehicle_tag', $vehicleTag)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required()
            );

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     * @param AddChargeScheduleRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function addChargeSchedule(string $vehicleTag, AddChargeScheduleRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/add_charge_schedule'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(
                TemplateParam::init('vehicle_tag', $vehicleTag)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required()
            );

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     * @param AddPreconditionScheduleRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function addPreconditionSchedule(string $vehicleTag, AddPreconditionScheduleRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/add_precondition_schedule'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(
                TemplateParam::init('vehicle_tag', $vehicleTag)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required()
            );

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     * @param AdjustVolumeRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function adjustMediaVolume(string $vehicleTag, AdjustVolumeRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/adjust_volume'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(
                TemplateParam::init('vehicle_tag', $vehicleTag)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required()
            );

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function startClimatePreconditioning(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/auto_conditioning_start'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function stopClimatePreconditioning(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/auto_conditioning_stop'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function cancelSoftwareUpdate(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/cancel_software_update'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function chargeMaxRange(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/charge_max_range'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function openChargePortDoor(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/charge_port_door_open'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function closeChargePortDoor(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/charge_port_door_close'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function chargeStandard(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/charge_standard'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function startCharging(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/charge_start'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function stopCharging(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/charge_stop'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Deactivates PIN to Drive and resets the associated PIN for supported firmware versions.
     *
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function clearPinToDriveAdmin(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/clear_pin_to_drive_admin'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function lockDoors(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/door_lock'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function unlockDoors(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/door_unlock'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Erases user data from the vehicle UI. Requires Guest Mode.
     *
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function eraseUserData(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/erase_user_data'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Briefly flashes vehicle headlights.
     *
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function flashLights(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/flash_lights'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     * @param GuestModeRequest $body
     *
     * @return ApiResponse Response from the API call
     */
    public function enableOrDisableGuestMode(string $vehicleTag, GuestModeRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/guest_mode'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(
                TemplateParam::init('vehicle_tag', $vehicleTag)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required()
            );

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function honkHorn(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/honk_horn'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $vehicleTag
     *
     * @return ApiResponse Response from the API call
     */
    public function nextFavoriteMediaTrack(string $vehicleTag): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/api/1/vehicles/{vehicle_tag}/command/media_next_fav'
        )
            ->auth('thirdpartytoken', 'bearerAuth')
            ->parameters(TemplateParam::init('vehicle_tag', $vehicleTag)->required());

        $_resHandler = $this->responseHandler()->type(CommandResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
