<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ActuateTrunkRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $whichTrunk;

    /**
     * @param string $whichTrunk
     */
    public function __construct(string $whichTrunk)
    {
        $this->whichTrunk = $whichTrunk;
    }

    /**
     * Returns Which Trunk.
     */
    public function getWhichTrunk(): string
    {
        return $this->whichTrunk;
    }

    /**
     * Sets Which Trunk.
     *
     * @required
     * @maps which_trunk
     */
    public function setWhichTrunk(string $whichTrunk): void
    {
        $this->whichTrunk = $whichTrunk;
    }

    /**
     * Converts the ActuateTrunkRequest object to a human-readable string representation.
     *
     * @return string The string representation of the ActuateTrunkRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ActuateTrunkRequest',
            ['whichTrunk' => $this->whichTrunk, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['which_trunk'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['which_trunk'] = $this->whichTrunk;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
