<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class AddPreconditionScheduleRequest implements \JsonSerializable
{
    /**
     * @var float
     */
    private $lat;

    /**
     * @var float
     */
    private $lon;

    /**
     * @var int
     */
    private $id;

    /**
     * @var string|null
     */
    private $daysOfWeek;

    /**
     * @var int|null
     */
    private $preconditionTime;

    /**
     * @var bool|null
     */
    private $oneTime;

    /**
     * @var bool
     */
    private $enabled;

    /**
     * @param float $lat
     * @param float $lon
     * @param int $id
     * @param bool $enabled
     */
    public function __construct(float $lat, float $lon, int $id, bool $enabled)
    {
        $this->lat = $lat;
        $this->lon = $lon;
        $this->id = $id;
        $this->enabled = $enabled;
    }

    /**
     * Returns Lat.
     */
    public function getLat(): float
    {
        return $this->lat;
    }

    /**
     * Sets Lat.
     *
     * @required
     * @maps lat
     */
    public function setLat(float $lat): void
    {
        $this->lat = $lat;
    }

    /**
     * Returns Lon.
     */
    public function getLon(): float
    {
        return $this->lon;
    }

    /**
     * Sets Lon.
     *
     * @required
     * @maps lon
     */
    public function setLon(float $lon): void
    {
        $this->lon = $lon;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Days of Week.
     */
    public function getDaysOfWeek(): ?string
    {
        return $this->daysOfWeek;
    }

    /**
     * Sets Days of Week.
     *
     * @maps days_of_week
     */
    public function setDaysOfWeek(?string $daysOfWeek): void
    {
        $this->daysOfWeek = $daysOfWeek;
    }

    /**
     * Returns Precondition Time.
     */
    public function getPreconditionTime(): ?int
    {
        return $this->preconditionTime;
    }

    /**
     * Sets Precondition Time.
     *
     * @maps precondition_time
     */
    public function setPreconditionTime(?int $preconditionTime): void
    {
        $this->preconditionTime = $preconditionTime;
    }

    /**
     * Returns One Time.
     */
    public function getOneTime(): ?bool
    {
        return $this->oneTime;
    }

    /**
     * Sets One Time.
     *
     * @maps one_time
     */
    public function setOneTime(?bool $oneTime): void
    {
        $this->oneTime = $oneTime;
    }

    /**
     * Returns Enabled.
     */
    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * Sets Enabled.
     *
     * @required
     * @maps enabled
     */
    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    /**
     * Converts the AddPreconditionScheduleRequest object to a human-readable string representation.
     *
     * @return string The string representation of the AddPreconditionScheduleRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AddPreconditionScheduleRequest',
            [
                'lat' => $this->lat,
                'lon' => $this->lon,
                'id' => $this->id,
                'daysOfWeek' => $this->daysOfWeek,
                'preconditionTime' => $this->preconditionTime,
                'oneTime' => $this->oneTime,
                'enabled' => $this->enabled,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['lat', 'lon', 'id', 'days_of_week', 'precondition_time', 'one_time', 'enabled'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['lat']                   = $this->lat;
        $json['lon']                   = $this->lon;
        $json['id']                    = $this->id;
        if (isset($this->daysOfWeek)) {
            $json['days_of_week']      = $this->daysOfWeek;
        }
        if (isset($this->preconditionTime)) {
            $json['precondition_time'] = $this->preconditionTime;
        }
        if (isset($this->oneTime)) {
            $json['one_time']          = $this->oneTime;
        }
        $json['enabled']               = $this->enabled;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
