<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargingLocation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var float|null
     */
    private $distanceMiles;

    /**
     * @var string|null
     */
    private $amenities;

    /**
     * @var int|null
     */
    private $availableStalls;

    /**
     * @var int|null
     */
    private $totalStalls;

    /**
     * @var bool|null
     */
    private $siteClosed;

    /**
     * @var string|null
     */
    private $billingInfo;

    /**
     * @var Location1|null
     */
    private $location;

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Distance Miles.
     */
    public function getDistanceMiles(): ?float
    {
        return $this->distanceMiles;
    }

    /**
     * Sets Distance Miles.
     *
     * @maps distance_miles
     */
    public function setDistanceMiles(?float $distanceMiles): void
    {
        $this->distanceMiles = $distanceMiles;
    }

    /**
     * Returns Amenities.
     */
    public function getAmenities(): ?string
    {
        return $this->amenities;
    }

    /**
     * Sets Amenities.
     *
     * @maps amenities
     */
    public function setAmenities(?string $amenities): void
    {
        $this->amenities = $amenities;
    }

    /**
     * Returns Available Stalls.
     */
    public function getAvailableStalls(): ?int
    {
        return $this->availableStalls;
    }

    /**
     * Sets Available Stalls.
     *
     * @maps available_stalls
     */
    public function setAvailableStalls(?int $availableStalls): void
    {
        $this->availableStalls = $availableStalls;
    }

    /**
     * Returns Total Stalls.
     */
    public function getTotalStalls(): ?int
    {
        return $this->totalStalls;
    }

    /**
     * Sets Total Stalls.
     *
     * @maps total_stalls
     */
    public function setTotalStalls(?int $totalStalls): void
    {
        $this->totalStalls = $totalStalls;
    }

    /**
     * Returns Site Closed.
     */
    public function getSiteClosed(): ?bool
    {
        return $this->siteClosed;
    }

    /**
     * Sets Site Closed.
     *
     * @maps site_closed
     */
    public function setSiteClosed(?bool $siteClosed): void
    {
        $this->siteClosed = $siteClosed;
    }

    /**
     * Returns Billing Info.
     */
    public function getBillingInfo(): ?string
    {
        return $this->billingInfo;
    }

    /**
     * Sets Billing Info.
     *
     * @maps billing_info
     */
    public function setBillingInfo(?string $billingInfo): void
    {
        $this->billingInfo = $billingInfo;
    }

    /**
     * Returns Location.
     */
    public function getLocation(): ?Location1
    {
        return $this->location;
    }

    /**
     * Sets Location.
     *
     * @maps location
     */
    public function setLocation(?Location1 $location): void
    {
        $this->location = $location;
    }

    /**
     * Converts the ChargingLocation object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingLocation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingLocation',
            [
                'name' => $this->name,
                'type' => $this->type,
                'distanceMiles' => $this->distanceMiles,
                'amenities' => $this->amenities,
                'availableStalls' => $this->availableStalls,
                'totalStalls' => $this->totalStalls,
                'siteClosed' => $this->siteClosed,
                'billingInfo' => $this->billingInfo,
                'location' => $this->location,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'name',
        'type',
        'distance_miles',
        'amenities',
        'available_stalls',
        'total_stalls',
        'site_closed',
        'billing_info',
        'location'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']             = $this->name;
        }
        if (isset($this->type)) {
            $json['type']             = $this->type;
        }
        if (isset($this->distanceMiles)) {
            $json['distance_miles']   = $this->distanceMiles;
        }
        if (isset($this->amenities)) {
            $json['amenities']        = $this->amenities;
        }
        if (isset($this->availableStalls)) {
            $json['available_stalls'] = $this->availableStalls;
        }
        if (isset($this->totalStalls)) {
            $json['total_stalls']     = $this->totalStalls;
        }
        if (isset($this->siteClosed)) {
            $json['site_closed']      = $this->siteClosed;
        }
        if (isset($this->billingInfo)) {
            $json['billing_info']     = $this->billingInfo;
        }
        if (isset($this->location)) {
            $json['location']         = $this->location;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
