<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargingInvoice implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $fileName;

    /**
     * @var string|null
     */
    private $contentId;

    /**
     * @var string|null
     */
    private $invoiceType;

    /**
     * Returns File Name.
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * Sets File Name.
     *
     * @maps fileName
     */
    public function setFileName(?string $fileName): void
    {
        $this->fileName = $fileName;
    }

    /**
     * Returns Content Id.
     */
    public function getContentId(): ?string
    {
        return $this->contentId;
    }

    /**
     * Sets Content Id.
     *
     * @maps contentId
     */
    public function setContentId(?string $contentId): void
    {
        $this->contentId = $contentId;
    }

    /**
     * Returns Invoice Type.
     */
    public function getInvoiceType(): ?string
    {
        return $this->invoiceType;
    }

    /**
     * Sets Invoice Type.
     *
     * @maps invoiceType
     */
    public function setInvoiceType(?string $invoiceType): void
    {
        $this->invoiceType = $invoiceType;
    }

    /**
     * Converts the ChargingInvoice object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingInvoice object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingInvoice',
            [
                'fileName' => $this->fileName,
                'contentId' => $this->contentId,
                'invoiceType' => $this->invoiceType,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['fileName', 'contentId', 'invoiceType'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fileName)) {
            $json['fileName']    = $this->fileName;
        }
        if (isset($this->contentId)) {
            $json['contentId']   = $this->contentId;
        }
        if (isset($this->invoiceType)) {
            $json['invoiceType'] = $this->invoiceType;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
