<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargingFee implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $sessionFeeId;

    /**
     * @var string|null
     */
    private $feeType;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var string|null
     */
    private $pricingType;

    /**
     * @var float|null
     */
    private $rateBase;

    /**
     * @var float|null
     */
    private $rateTier1;

    /**
     * @var float|null
     */
    private $rateTier2;

    /**
     * @var array
     */
    private $rateTier3 = [];

    /**
     * @var array
     */
    private $rateTier4 = [];

    /**
     * @var float|null
     */
    private $usageBase;

    /**
     * @var float|null
     */
    private $usageTier1;

    /**
     * @var float|null
     */
    private $usageTier2;

    /**
     * @var array
     */
    private $usageTier3 = [];

    /**
     * @var array
     */
    private $usageTier4 = [];

    /**
     * @var float|null
     */
    private $totalBase;

    /**
     * @var float|null
     */
    private $totalTier1;

    /**
     * @var float|null
     */
    private $totalTier2;

    /**
     * @var float|null
     */
    private $totalTier3;

    /**
     * @var float|null
     */
    private $totalTier4;

    /**
     * @var float|null
     */
    private $totalDue;

    /**
     * @var float|null
     */
    private $netDue;

    /**
     * @var string|null
     */
    private $uom;

    /**
     * @var bool|null
     */
    private $isPaid;

    /**
     * @var string|null
     */
    private $status;

    /**
     * Returns Session Fee Id.
     */
    public function getSessionFeeId(): ?int
    {
        return $this->sessionFeeId;
    }

    /**
     * Sets Session Fee Id.
     *
     * @maps sessionFeeId
     */
    public function setSessionFeeId(?int $sessionFeeId): void
    {
        $this->sessionFeeId = $sessionFeeId;
    }

    /**
     * Returns Fee Type.
     */
    public function getFeeType(): ?string
    {
        return $this->feeType;
    }

    /**
     * Sets Fee Type.
     *
     * @maps feeType
     */
    public function setFeeType(?string $feeType): void
    {
        $this->feeType = $feeType;
    }

    /**
     * Returns Currency Code.
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     *
     * @maps currencyCode
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Pricing Type.
     */
    public function getPricingType(): ?string
    {
        return $this->pricingType;
    }

    /**
     * Sets Pricing Type.
     *
     * @maps pricingType
     */
    public function setPricingType(?string $pricingType): void
    {
        $this->pricingType = $pricingType;
    }

    /**
     * Returns Rate Base.
     */
    public function getRateBase(): ?float
    {
        return $this->rateBase;
    }

    /**
     * Sets Rate Base.
     *
     * @maps rateBase
     */
    public function setRateBase(?float $rateBase): void
    {
        $this->rateBase = $rateBase;
    }

    /**
     * Returns Rate Tier 1.
     */
    public function getRateTier1(): ?float
    {
        return $this->rateTier1;
    }

    /**
     * Sets Rate Tier 1.
     *
     * @maps rateTier1
     */
    public function setRateTier1(?float $rateTier1): void
    {
        $this->rateTier1 = $rateTier1;
    }

    /**
     * Returns Rate Tier 2.
     */
    public function getRateTier2(): ?float
    {
        return $this->rateTier2;
    }

    /**
     * Sets Rate Tier 2.
     *
     * @maps rateTier2
     */
    public function setRateTier2(?float $rateTier2): void
    {
        $this->rateTier2 = $rateTier2;
    }

    /**
     * Returns Rate Tier 3.
     */
    public function getRateTier3(): ?float
    {
        if (count($this->rateTier3) == 0) {
            return null;
        }
        return $this->rateTier3['value'];
    }

    /**
     * Sets Rate Tier 3.
     *
     * @maps rateTier3
     */
    public function setRateTier3(?float $rateTier3): void
    {
        $this->rateTier3['value'] = $rateTier3;
    }

    /**
     * Unsets Rate Tier 3.
     */
    public function unsetRateTier3(): void
    {
        $this->rateTier3 = [];
    }

    /**
     * Returns Rate Tier 4.
     */
    public function getRateTier4(): ?float
    {
        if (count($this->rateTier4) == 0) {
            return null;
        }
        return $this->rateTier4['value'];
    }

    /**
     * Sets Rate Tier 4.
     *
     * @maps rateTier4
     */
    public function setRateTier4(?float $rateTier4): void
    {
        $this->rateTier4['value'] = $rateTier4;
    }

    /**
     * Unsets Rate Tier 4.
     */
    public function unsetRateTier4(): void
    {
        $this->rateTier4 = [];
    }

    /**
     * Returns Usage Base.
     */
    public function getUsageBase(): ?float
    {
        return $this->usageBase;
    }

    /**
     * Sets Usage Base.
     *
     * @maps usageBase
     */
    public function setUsageBase(?float $usageBase): void
    {
        $this->usageBase = $usageBase;
    }

    /**
     * Returns Usage Tier 1.
     */
    public function getUsageTier1(): ?float
    {
        return $this->usageTier1;
    }

    /**
     * Sets Usage Tier 1.
     *
     * @maps usageTier1
     */
    public function setUsageTier1(?float $usageTier1): void
    {
        $this->usageTier1 = $usageTier1;
    }

    /**
     * Returns Usage Tier 2.
     */
    public function getUsageTier2(): ?float
    {
        return $this->usageTier2;
    }

    /**
     * Sets Usage Tier 2.
     *
     * @maps usageTier2
     */
    public function setUsageTier2(?float $usageTier2): void
    {
        $this->usageTier2 = $usageTier2;
    }

    /**
     * Returns Usage Tier 3.
     */
    public function getUsageTier3(): ?float
    {
        if (count($this->usageTier3) == 0) {
            return null;
        }
        return $this->usageTier3['value'];
    }

    /**
     * Sets Usage Tier 3.
     *
     * @maps usageTier3
     */
    public function setUsageTier3(?float $usageTier3): void
    {
        $this->usageTier3['value'] = $usageTier3;
    }

    /**
     * Unsets Usage Tier 3.
     */
    public function unsetUsageTier3(): void
    {
        $this->usageTier3 = [];
    }

    /**
     * Returns Usage Tier 4.
     */
    public function getUsageTier4(): ?float
    {
        if (count($this->usageTier4) == 0) {
            return null;
        }
        return $this->usageTier4['value'];
    }

    /**
     * Sets Usage Tier 4.
     *
     * @maps usageTier4
     */
    public function setUsageTier4(?float $usageTier4): void
    {
        $this->usageTier4['value'] = $usageTier4;
    }

    /**
     * Unsets Usage Tier 4.
     */
    public function unsetUsageTier4(): void
    {
        $this->usageTier4 = [];
    }

    /**
     * Returns Total Base.
     */
    public function getTotalBase(): ?float
    {
        return $this->totalBase;
    }

    /**
     * Sets Total Base.
     *
     * @maps totalBase
     */
    public function setTotalBase(?float $totalBase): void
    {
        $this->totalBase = $totalBase;
    }

    /**
     * Returns Total Tier 1.
     */
    public function getTotalTier1(): ?float
    {
        return $this->totalTier1;
    }

    /**
     * Sets Total Tier 1.
     *
     * @maps totalTier1
     */
    public function setTotalTier1(?float $totalTier1): void
    {
        $this->totalTier1 = $totalTier1;
    }

    /**
     * Returns Total Tier 2.
     */
    public function getTotalTier2(): ?float
    {
        return $this->totalTier2;
    }

    /**
     * Sets Total Tier 2.
     *
     * @maps totalTier2
     */
    public function setTotalTier2(?float $totalTier2): void
    {
        $this->totalTier2 = $totalTier2;
    }

    /**
     * Returns Total Tier 3.
     */
    public function getTotalTier3(): ?float
    {
        return $this->totalTier3;
    }

    /**
     * Sets Total Tier 3.
     *
     * @maps totalTier3
     */
    public function setTotalTier3(?float $totalTier3): void
    {
        $this->totalTier3 = $totalTier3;
    }

    /**
     * Returns Total Tier 4.
     */
    public function getTotalTier4(): ?float
    {
        return $this->totalTier4;
    }

    /**
     * Sets Total Tier 4.
     *
     * @maps totalTier4
     */
    public function setTotalTier4(?float $totalTier4): void
    {
        $this->totalTier4 = $totalTier4;
    }

    /**
     * Returns Total Due.
     */
    public function getTotalDue(): ?float
    {
        return $this->totalDue;
    }

    /**
     * Sets Total Due.
     *
     * @maps totalDue
     */
    public function setTotalDue(?float $totalDue): void
    {
        $this->totalDue = $totalDue;
    }

    /**
     * Returns Net Due.
     */
    public function getNetDue(): ?float
    {
        return $this->netDue;
    }

    /**
     * Sets Net Due.
     *
     * @maps netDue
     */
    public function setNetDue(?float $netDue): void
    {
        $this->netDue = $netDue;
    }

    /**
     * Returns Uom.
     */
    public function getUom(): ?string
    {
        return $this->uom;
    }

    /**
     * Sets Uom.
     *
     * @maps uom
     */
    public function setUom(?string $uom): void
    {
        $this->uom = $uom;
    }

    /**
     * Returns Is Paid.
     */
    public function getIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    /**
     * Sets Is Paid.
     *
     * @maps isPaid
     */
    public function setIsPaid(?bool $isPaid): void
    {
        $this->isPaid = $isPaid;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the ChargingFee object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingFee object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingFee',
            [
                'sessionFeeId' => $this->sessionFeeId,
                'feeType' => $this->feeType,
                'currencyCode' => $this->currencyCode,
                'pricingType' => $this->pricingType,
                'rateBase' => $this->rateBase,
                'rateTier1' => $this->rateTier1,
                'rateTier2' => $this->rateTier2,
                'rateTier3' => $this->getRateTier3(),
                'rateTier4' => $this->getRateTier4(),
                'usageBase' => $this->usageBase,
                'usageTier1' => $this->usageTier1,
                'usageTier2' => $this->usageTier2,
                'usageTier3' => $this->getUsageTier3(),
                'usageTier4' => $this->getUsageTier4(),
                'totalBase' => $this->totalBase,
                'totalTier1' => $this->totalTier1,
                'totalTier2' => $this->totalTier2,
                'totalTier3' => $this->totalTier3,
                'totalTier4' => $this->totalTier4,
                'totalDue' => $this->totalDue,
                'netDue' => $this->netDue,
                'uom' => $this->uom,
                'isPaid' => $this->isPaid,
                'status' => $this->status,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sessionFeeId',
        'feeType',
        'currencyCode',
        'pricingType',
        'rateBase',
        'rateTier1',
        'rateTier2',
        'rateTier3',
        'rateTier4',
        'usageBase',
        'usageTier1',
        'usageTier2',
        'usageTier3',
        'usageTier4',
        'totalBase',
        'totalTier1',
        'totalTier2',
        'totalTier3',
        'totalTier4',
        'totalDue',
        'netDue',
        'uom',
        'isPaid',
        'status'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->sessionFeeId)) {
            $json['sessionFeeId'] = $this->sessionFeeId;
        }
        if (isset($this->feeType)) {
            $json['feeType']      = $this->feeType;
        }
        if (isset($this->currencyCode)) {
            $json['currencyCode'] = $this->currencyCode;
        }
        if (isset($this->pricingType)) {
            $json['pricingType']  = $this->pricingType;
        }
        if (isset($this->rateBase)) {
            $json['rateBase']     = $this->rateBase;
        }
        if (isset($this->rateTier1)) {
            $json['rateTier1']    = $this->rateTier1;
        }
        if (isset($this->rateTier2)) {
            $json['rateTier2']    = $this->rateTier2;
        }
        if (!empty($this->rateTier3)) {
            $json['rateTier3']    = $this->rateTier3['value'];
        }
        if (!empty($this->rateTier4)) {
            $json['rateTier4']    = $this->rateTier4['value'];
        }
        if (isset($this->usageBase)) {
            $json['usageBase']    = $this->usageBase;
        }
        if (isset($this->usageTier1)) {
            $json['usageTier1']   = $this->usageTier1;
        }
        if (isset($this->usageTier2)) {
            $json['usageTier2']   = $this->usageTier2;
        }
        if (!empty($this->usageTier3)) {
            $json['usageTier3']   = $this->usageTier3['value'];
        }
        if (!empty($this->usageTier4)) {
            $json['usageTier4']   = $this->usageTier4['value'];
        }
        if (isset($this->totalBase)) {
            $json['totalBase']    = $this->totalBase;
        }
        if (isset($this->totalTier1)) {
            $json['totalTier1']   = $this->totalTier1;
        }
        if (isset($this->totalTier2)) {
            $json['totalTier2']   = $this->totalTier2;
        }
        if (isset($this->totalTier3)) {
            $json['totalTier3']   = $this->totalTier3;
        }
        if (isset($this->totalTier4)) {
            $json['totalTier4']   = $this->totalTier4;
        }
        if (isset($this->totalDue)) {
            $json['totalDue']     = $this->totalDue;
        }
        if (isset($this->netDue)) {
            $json['netDue']       = $this->netDue;
        }
        if (isset($this->uom)) {
            $json['uom']          = $this->uom;
        }
        if (isset($this->isPaid)) {
            $json['isPaid']       = $this->isPaid;
        }
        if (isset($this->status)) {
            $json['status']       = $this->status;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
