<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargeHistory implements \JsonSerializable
{
    /**
     * @var ChargeStartTime
     */
    private $chargeStartTime;

    /**
     * @var ChargeDuration
     */
    private $chargeDuration;

    /**
     * @var int
     */
    private $energyAddedWh;

    /**
     * @param ChargeStartTime $chargeStartTime
     * @param ChargeDuration $chargeDuration
     * @param int $energyAddedWh
     */
    public function __construct(ChargeStartTime $chargeStartTime, ChargeDuration $chargeDuration, int $energyAddedWh)
    {
        $this->chargeStartTime = $chargeStartTime;
        $this->chargeDuration = $chargeDuration;
        $this->energyAddedWh = $energyAddedWh;
    }

    /**
     * Returns Charge Start Time.
     */
    public function getChargeStartTime(): ChargeStartTime
    {
        return $this->chargeStartTime;
    }

    /**
     * Sets Charge Start Time.
     *
     * @required
     * @maps charge_start_time
     */
    public function setChargeStartTime(ChargeStartTime $chargeStartTime): void
    {
        $this->chargeStartTime = $chargeStartTime;
    }

    /**
     * Returns Charge Duration.
     */
    public function getChargeDuration(): ChargeDuration
    {
        return $this->chargeDuration;
    }

    /**
     * Sets Charge Duration.
     *
     * @required
     * @maps charge_duration
     */
    public function setChargeDuration(ChargeDuration $chargeDuration): void
    {
        $this->chargeDuration = $chargeDuration;
    }

    /**
     * Returns Energy Added Wh.
     */
    public function getEnergyAddedWh(): int
    {
        return $this->energyAddedWh;
    }

    /**
     * Sets Energy Added Wh.
     *
     * @required
     * @maps energy_added_wh
     */
    public function setEnergyAddedWh(int $energyAddedWh): void
    {
        $this->energyAddedWh = $energyAddedWh;
    }

    /**
     * Converts the ChargeHistory object to a human-readable string representation.
     *
     * @return string The string representation of the ChargeHistory object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargeHistory',
            [
                'chargeStartTime' => $this->chargeStartTime,
                'chargeDuration' => $this->chargeDuration,
                'energyAddedWh' => $this->energyAddedWh,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['charge_start_time', 'charge_duration', 'energy_added_wh'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['charge_start_time'] = $this->chargeStartTime;
        $json['charge_duration']   = $this->chargeDuration;
        $json['energy_added_wh']   = $this->energyAddedWh;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
