<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargingPeriod implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $startDateTime;

    /**
     * @var ChargingDimension[]|null
     */
    private $dimensions;

    /**
     * Returns Start Date Time.
     */
    public function getStartDateTime(): ?string
    {
        return $this->startDateTime;
    }

    /**
     * Sets Start Date Time.
     *
     * @maps start_date_time
     */
    public function setStartDateTime(?string $startDateTime): void
    {
        $this->startDateTime = $startDateTime;
    }

    /**
     * Returns Dimensions.
     *
     * @return ChargingDimension[]|null
     */
    public function getDimensions(): ?array
    {
        return $this->dimensions;
    }

    /**
     * Sets Dimensions.
     *
     * @maps dimensions
     *
     * @param ChargingDimension[]|null $dimensions
     */
    public function setDimensions(?array $dimensions): void
    {
        $this->dimensions = $dimensions;
    }

    /**
     * Converts the ChargingPeriod object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingPeriod object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingPeriod',
            [
                'startDateTime' => $this->startDateTime,
                'dimensions' => $this->dimensions,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['start_date_time', 'dimensions'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->startDateTime)) {
            $json['start_date_time'] = $this->startDateTime;
        }
        if (isset($this->dimensions)) {
            $json['dimensions']      = $this->dimensions;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
