<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;
use TeslaFleetManagementApiLib\Utils\DateTimeHelper;

class ChargingHistoryItem implements \JsonSerializable
{
    /**
     * @var int
     */
    private $sessionId;

    /**
     * @var string
     */
    private $vin;

    /**
     * @var string|null
     */
    private $siteLocationName;

    /**
     * @var \DateTime|null
     */
    private $chargeStartDateTime;

    /**
     * @var \DateTime|null
     */
    private $chargeStopDateTime;

    /**
     * @var \DateTime|null
     */
    private $unlatchDateTime;

    /**
     * @var string|null
     */
    private $countryCode;

    /**
     * @var ChargingFee[]|null
     */
    private $fees;

    /**
     * @var string|null
     */
    private $billingType;

    /**
     * @var ChargingInvoice[]|null
     */
    private $invoices;

    /**
     * @var string|null
     */
    private $vehicleMakeType;

    /**
     * @param int $sessionId
     * @param string $vin
     */
    public function __construct(int $sessionId, string $vin)
    {
        $this->sessionId = $sessionId;
        $this->vin = $vin;
    }

    /**
     * Returns Session Id.
     */
    public function getSessionId(): int
    {
        return $this->sessionId;
    }

    /**
     * Sets Session Id.
     *
     * @required
     * @maps sessionId
     */
    public function setSessionId(int $sessionId): void
    {
        $this->sessionId = $sessionId;
    }

    /**
     * Returns Vin.
     */
    public function getVin(): string
    {
        return $this->vin;
    }

    /**
     * Sets Vin.
     *
     * @required
     * @maps vin
     */
    public function setVin(string $vin): void
    {
        $this->vin = $vin;
    }

    /**
     * Returns Site Location Name.
     */
    public function getSiteLocationName(): ?string
    {
        return $this->siteLocationName;
    }

    /**
     * Sets Site Location Name.
     *
     * @maps siteLocationName
     */
    public function setSiteLocationName(?string $siteLocationName): void
    {
        $this->siteLocationName = $siteLocationName;
    }

    /**
     * Returns Charge Start Date Time.
     */
    public function getChargeStartDateTime(): ?\DateTime
    {
        return $this->chargeStartDateTime;
    }

    /**
     * Sets Charge Start Date Time.
     *
     * @maps chargeStartDateTime
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setChargeStartDateTime(?\DateTime $chargeStartDateTime): void
    {
        $this->chargeStartDateTime = $chargeStartDateTime;
    }

    /**
     * Returns Charge Stop Date Time.
     */
    public function getChargeStopDateTime(): ?\DateTime
    {
        return $this->chargeStopDateTime;
    }

    /**
     * Sets Charge Stop Date Time.
     *
     * @maps chargeStopDateTime
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setChargeStopDateTime(?\DateTime $chargeStopDateTime): void
    {
        $this->chargeStopDateTime = $chargeStopDateTime;
    }

    /**
     * Returns Unlatch Date Time.
     */
    public function getUnlatchDateTime(): ?\DateTime
    {
        return $this->unlatchDateTime;
    }

    /**
     * Sets Unlatch Date Time.
     *
     * @maps unlatchDateTime
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUnlatchDateTime(?\DateTime $unlatchDateTime): void
    {
        $this->unlatchDateTime = $unlatchDateTime;
    }

    /**
     * Returns Country Code.
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * Sets Country Code.
     *
     * @maps countryCode
     */
    public function setCountryCode(?string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    /**
     * Returns Fees.
     *
     * @return ChargingFee[]|null
     */
    public function getFees(): ?array
    {
        return $this->fees;
    }

    /**
     * Sets Fees.
     *
     * @maps fees
     *
     * @param ChargingFee[]|null $fees
     */
    public function setFees(?array $fees): void
    {
        $this->fees = $fees;
    }

    /**
     * Returns Billing Type.
     */
    public function getBillingType(): ?string
    {
        return $this->billingType;
    }

    /**
     * Sets Billing Type.
     *
     * @maps billingType
     */
    public function setBillingType(?string $billingType): void
    {
        $this->billingType = $billingType;
    }

    /**
     * Returns Invoices.
     *
     * @return ChargingInvoice[]|null
     */
    public function getInvoices(): ?array
    {
        return $this->invoices;
    }

    /**
     * Sets Invoices.
     *
     * @maps invoices
     *
     * @param ChargingInvoice[]|null $invoices
     */
    public function setInvoices(?array $invoices): void
    {
        $this->invoices = $invoices;
    }

    /**
     * Returns Vehicle Make Type.
     */
    public function getVehicleMakeType(): ?string
    {
        return $this->vehicleMakeType;
    }

    /**
     * Sets Vehicle Make Type.
     *
     * @maps vehicleMakeType
     */
    public function setVehicleMakeType(?string $vehicleMakeType): void
    {
        $this->vehicleMakeType = $vehicleMakeType;
    }

    /**
     * Converts the ChargingHistoryItem object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingHistoryItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingHistoryItem',
            [
                'sessionId' => $this->sessionId,
                'vin' => $this->vin,
                'siteLocationName' => $this->siteLocationName,
                'chargeStartDateTime' => $this->chargeStartDateTime,
                'chargeStopDateTime' => $this->chargeStopDateTime,
                'unlatchDateTime' => $this->unlatchDateTime,
                'countryCode' => $this->countryCode,
                'fees' => $this->fees,
                'billingType' => $this->billingType,
                'invoices' => $this->invoices,
                'vehicleMakeType' => $this->vehicleMakeType,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sessionId',
        'vin',
        'siteLocationName',
        'chargeStartDateTime',
        'chargeStopDateTime',
        'unlatchDateTime',
        'countryCode',
        'fees',
        'billingType',
        'invoices',
        'vehicleMakeType'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['sessionId']               = $this->sessionId;
        $json['vin']                     = $this->vin;
        if (isset($this->siteLocationName)) {
            $json['siteLocationName']    = $this->siteLocationName;
        }
        if (isset($this->chargeStartDateTime)) {
            $json['chargeStartDateTime'] = DateTimeHelper::toRfc3339DateTime($this->chargeStartDateTime);
        }
        if (isset($this->chargeStopDateTime)) {
            $json['chargeStopDateTime']  = DateTimeHelper::toRfc3339DateTime($this->chargeStopDateTime);
        }
        if (isset($this->unlatchDateTime)) {
            $json['unlatchDateTime']     = DateTimeHelper::toRfc3339DateTime($this->unlatchDateTime);
        }
        if (isset($this->countryCode)) {
            $json['countryCode']         = $this->countryCode;
        }
        if (isset($this->fees)) {
            $json['fees']                = $this->fees;
        }
        if (isset($this->billingType)) {
            $json['billingType']         = $this->billingType;
        }
        if (isset($this->invoices)) {
            $json['invoices']            = $this->invoices;
        }
        if (isset($this->vehicleMakeType)) {
            $json['vehicleMakeType']     = $this->vehicleMakeType;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
