<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargingSession implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $vin;

    /**
     * @var string|null
     */
    private $model;

    /**
     * @var string|null
     */
    private $startDateTime;

    /**
     * @var string|null
     */
    private $stopDateTime;

    /**
     * @var float|null
     */
    private $totalEnergy;

    /**
     * @var float|null
     */
    private $totalTime;

    /**
     * @var TotalCost|null
     */
    private $totalCost;

    /**
     * @var Location|null
     */
    private $location;

    /**
     * @var ChargingPeriod[]|null
     */
    private $chargingPeriods;

    /**
     * @var Tariffs|null
     */
    private $tariffs;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Vin.
     */
    public function getVin(): ?string
    {
        return $this->vin;
    }

    /**
     * Sets Vin.
     *
     * @maps vin
     */
    public function setVin(?string $vin): void
    {
        $this->vin = $vin;
    }

    /**
     * Returns Model.
     */
    public function getModel(): ?string
    {
        return $this->model;
    }

    /**
     * Sets Model.
     *
     * @maps model
     */
    public function setModel(?string $model): void
    {
        $this->model = $model;
    }

    /**
     * Returns Start Date Time.
     */
    public function getStartDateTime(): ?string
    {
        return $this->startDateTime;
    }

    /**
     * Sets Start Date Time.
     *
     * @maps start_date_time
     */
    public function setStartDateTime(?string $startDateTime): void
    {
        $this->startDateTime = $startDateTime;
    }

    /**
     * Returns Stop Date Time.
     */
    public function getStopDateTime(): ?string
    {
        return $this->stopDateTime;
    }

    /**
     * Sets Stop Date Time.
     *
     * @maps stop_date_time
     */
    public function setStopDateTime(?string $stopDateTime): void
    {
        $this->stopDateTime = $stopDateTime;
    }

    /**
     * Returns Total Energy.
     */
    public function getTotalEnergy(): ?float
    {
        return $this->totalEnergy;
    }

    /**
     * Sets Total Energy.
     *
     * @maps total_energy
     */
    public function setTotalEnergy(?float $totalEnergy): void
    {
        $this->totalEnergy = $totalEnergy;
    }

    /**
     * Returns Total Time.
     */
    public function getTotalTime(): ?float
    {
        return $this->totalTime;
    }

    /**
     * Sets Total Time.
     *
     * @maps total_time
     */
    public function setTotalTime(?float $totalTime): void
    {
        $this->totalTime = $totalTime;
    }

    /**
     * Returns Total Cost.
     */
    public function getTotalCost(): ?TotalCost
    {
        return $this->totalCost;
    }

    /**
     * Sets Total Cost.
     *
     * @maps total_cost
     */
    public function setTotalCost(?TotalCost $totalCost): void
    {
        $this->totalCost = $totalCost;
    }

    /**
     * Returns Location.
     */
    public function getLocation(): ?Location
    {
        return $this->location;
    }

    /**
     * Sets Location.
     *
     * @maps location
     */
    public function setLocation(?Location $location): void
    {
        $this->location = $location;
    }

    /**
     * Returns Charging Periods.
     *
     * @return ChargingPeriod[]|null
     */
    public function getChargingPeriods(): ?array
    {
        return $this->chargingPeriods;
    }

    /**
     * Sets Charging Periods.
     *
     * @maps charging_periods
     *
     * @param ChargingPeriod[]|null $chargingPeriods
     */
    public function setChargingPeriods(?array $chargingPeriods): void
    {
        $this->chargingPeriods = $chargingPeriods;
    }

    /**
     * Returns Tariffs.
     */
    public function getTariffs(): ?Tariffs
    {
        return $this->tariffs;
    }

    /**
     * Sets Tariffs.
     *
     * @maps tariffs
     */
    public function setTariffs(?Tariffs $tariffs): void
    {
        $this->tariffs = $tariffs;
    }

    /**
     * Converts the ChargingSession object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingSession object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingSession',
            [
                'id' => $this->id,
                'vin' => $this->vin,
                'model' => $this->model,
                'startDateTime' => $this->startDateTime,
                'stopDateTime' => $this->stopDateTime,
                'totalEnergy' => $this->totalEnergy,
                'totalTime' => $this->totalTime,
                'totalCost' => $this->totalCost,
                'location' => $this->location,
                'chargingPeriods' => $this->chargingPeriods,
                'tariffs' => $this->tariffs,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'vin',
        'model',
        'start_date_time',
        'stop_date_time',
        'total_energy',
        'total_time',
        'total_cost',
        'location',
        'charging_periods',
        'tariffs'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->vin)) {
            $json['vin']              = $this->vin;
        }
        if (isset($this->model)) {
            $json['model']            = $this->model;
        }
        if (isset($this->startDateTime)) {
            $json['start_date_time']  = $this->startDateTime;
        }
        if (isset($this->stopDateTime)) {
            $json['stop_date_time']   = $this->stopDateTime;
        }
        if (isset($this->totalEnergy)) {
            $json['total_energy']     = $this->totalEnergy;
        }
        if (isset($this->totalTime)) {
            $json['total_time']       = $this->totalTime;
        }
        if (isset($this->totalCost)) {
            $json['total_cost']       = $this->totalCost;
        }
        if (isset($this->location)) {
            $json['location']         = $this->location;
        }
        if (isset($this->chargingPeriods)) {
            $json['charging_periods'] = $this->chargingPeriods;
        }
        if (isset($this->tariffs)) {
            $json['tariffs']          = $this->tariffs;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
