<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ChargingSessionsData implements \JsonSerializable
{
    /**
     * @var ChargingSession[]|null
     */
    private $data;

    /**
     * @var int|null
     */
    private $statusCode;

    /**
     * @var string|null
     */
    private $statusMessage;

    /**
     * @var array<string,string>|null
     */
    private $timestamp;

    /**
     * Returns Data.
     *
     * @return ChargingSession[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @maps data
     *
     * @param ChargingSession[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Returns Status Code.
     */
    public function getStatusCode(): ?int
    {
        return $this->statusCode;
    }

    /**
     * Sets Status Code.
     *
     * @maps status_code
     */
    public function setStatusCode(?int $statusCode): void
    {
        $this->statusCode = $statusCode;
    }

    /**
     * Returns Status Message.
     */
    public function getStatusMessage(): ?string
    {
        return $this->statusMessage;
    }

    /**
     * Sets Status Message.
     *
     * @maps status_message
     */
    public function setStatusMessage(?string $statusMessage): void
    {
        $this->statusMessage = $statusMessage;
    }

    /**
     * Returns Timestamp.
     *
     * @return array<string,string>|null
     */
    public function getTimestamp(): ?array
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     *
     * @param array<string,string>|null $timestamp
     */
    public function setTimestamp(?array $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Converts the ChargingSessionsData object to a human-readable string representation.
     *
     * @return string The string representation of the ChargingSessionsData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChargingSessionsData',
            [
                'data' => $this->data,
                'statusCode' => $this->statusCode,
                'statusMessage' => $this->statusMessage,
                'timestamp' => $this->timestamp,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['data', 'status_code', 'status_message', 'timestamp'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->data)) {
            $json['data']           = $this->data;
        }
        if (isset($this->statusCode)) {
            $json['status_code']    = $this->statusCode;
        }
        if (isset($this->statusMessage)) {
            $json['status_message'] = $this->statusMessage;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']      = $this->timestamp;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
