<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

class DefaultRealMode
{
    public const AUTONOMOUS = 'autonomous';

    public const SELF_CONSUMPTION = 'self_consumption';
}
