<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class Driver implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $myTeslaUniqueId;

    /**
     * @var int|null
     */
    private $userId;

    /**
     * @var string|null
     */
    private $userIdS;

    /**
     * @var string|null
     */
    private $vaultUuid;

    /**
     * @var string|null
     */
    private $driverFirstName;

    /**
     * @var string|null
     */
    private $driverLastName;

    /**
     * @var array|null
     */
    private $granularAccess;

    /**
     * @var string[]|null
     */
    private $activePubkeys;

    /**
     * @var string|null
     */
    private $publicKey;

    /**
     * Returns My Tesla Unique Id.
     */
    public function getMyTeslaUniqueId(): ?int
    {
        return $this->myTeslaUniqueId;
    }

    /**
     * Sets My Tesla Unique Id.
     *
     * @maps my_tesla_unique_id
     */
    public function setMyTeslaUniqueId(?int $myTeslaUniqueId): void
    {
        $this->myTeslaUniqueId = $myTeslaUniqueId;
    }

    /**
     * Returns User Id.
     */
    public function getUserId(): ?int
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     *
     * @maps user_id
     */
    public function setUserId(?int $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns User Id S.
     */
    public function getUserIdS(): ?string
    {
        return $this->userIdS;
    }

    /**
     * Sets User Id S.
     *
     * @maps user_id_s
     */
    public function setUserIdS(?string $userIdS): void
    {
        $this->userIdS = $userIdS;
    }

    /**
     * Returns Vault Uuid.
     */
    public function getVaultUuid(): ?string
    {
        return $this->vaultUuid;
    }

    /**
     * Sets Vault Uuid.
     *
     * @maps vault_uuid
     */
    public function setVaultUuid(?string $vaultUuid): void
    {
        $this->vaultUuid = $vaultUuid;
    }

    /**
     * Returns Driver First Name.
     */
    public function getDriverFirstName(): ?string
    {
        return $this->driverFirstName;
    }

    /**
     * Sets Driver First Name.
     *
     * @maps driver_first_name
     */
    public function setDriverFirstName(?string $driverFirstName): void
    {
        $this->driverFirstName = $driverFirstName;
    }

    /**
     * Returns Driver Last Name.
     */
    public function getDriverLastName(): ?string
    {
        return $this->driverLastName;
    }

    /**
     * Sets Driver Last Name.
     *
     * @maps driver_last_name
     */
    public function setDriverLastName(?string $driverLastName): void
    {
        $this->driverLastName = $driverLastName;
    }

    /**
     * Returns Granular Access.
     */
    public function getGranularAccess(): ?array
    {
        return $this->granularAccess;
    }

    /**
     * Sets Granular Access.
     *
     * @maps granular_access
     */
    public function setGranularAccess(?array $granularAccess): void
    {
        $this->granularAccess = $granularAccess;
    }

    /**
     * Returns Active Pubkeys.
     *
     * @return string[]|null
     */
    public function getActivePubkeys(): ?array
    {
        return $this->activePubkeys;
    }

    /**
     * Sets Active Pubkeys.
     *
     * @maps active_pubkeys
     *
     * @param string[]|null $activePubkeys
     */
    public function setActivePubkeys(?array $activePubkeys): void
    {
        $this->activePubkeys = $activePubkeys;
    }

    /**
     * Returns Public Key.
     */
    public function getPublicKey(): ?string
    {
        return $this->publicKey;
    }

    /**
     * Sets Public Key.
     *
     * @maps public_key
     */
    public function setPublicKey(?string $publicKey): void
    {
        $this->publicKey = $publicKey;
    }

    /**
     * Converts the Driver object to a human-readable string representation.
     *
     * @return string The string representation of the Driver object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Driver',
            [
                'myTeslaUniqueId' => $this->myTeslaUniqueId,
                'userId' => $this->userId,
                'userIdS' => $this->userIdS,
                'vaultUuid' => $this->vaultUuid,
                'driverFirstName' => $this->driverFirstName,
                'driverLastName' => $this->driverLastName,
                'granularAccess' => $this->granularAccess,
                'activePubkeys' => $this->activePubkeys,
                'publicKey' => $this->publicKey,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'my_tesla_unique_id',
        'user_id',
        'user_id_s',
        'vault_uuid',
        'driver_first_name',
        'driver_last_name',
        'granular_access',
        'active_pubkeys',
        'public_key'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->myTeslaUniqueId)) {
            $json['my_tesla_unique_id'] = $this->myTeslaUniqueId;
        }
        if (isset($this->userId)) {
            $json['user_id']            = $this->userId;
        }
        if (isset($this->userIdS)) {
            $json['user_id_s']          = $this->userIdS;
        }
        if (isset($this->vaultUuid)) {
            $json['vault_uuid']         = $this->vaultUuid;
        }
        if (isset($this->driverFirstName)) {
            $json['driver_first_name']  = $this->driverFirstName;
        }
        if (isset($this->driverLastName)) {
            $json['driver_last_name']   = $this->driverLastName;
        }
        if (isset($this->granularAccess)) {
            $json['granular_access']    = $this->granularAccess;
        }
        if (isset($this->activePubkeys)) {
            $json['active_pubkeys']     = $this->activePubkeys;
        }
        if (isset($this->publicKey)) {
            $json['public_key']         = $this->publicKey;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
