<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class EnterprisePayerRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $role;

    /**
     * @var string|null
     */
    private $federationId;

    /**
     * @var string|null
     */
    private $accountId;

    /**
     * @param string $role
     */
    public function __construct(string $role)
    {
        $this->role = $role;
    }

    /**
     * Returns Role.
     */
    public function getRole(): string
    {
        return $this->role;
    }

    /**
     * Sets Role.
     *
     * @required
     * @maps role
     */
    public function setRole(string $role): void
    {
        $this->role = $role;
    }

    /**
     * Returns Federation Id.
     */
    public function getFederationId(): ?string
    {
        return $this->federationId;
    }

    /**
     * Sets Federation Id.
     *
     * @maps federation_id
     */
    public function setFederationId(?string $federationId): void
    {
        $this->federationId = $federationId;
    }

    /**
     * Returns Account Id.
     */
    public function getAccountId(): ?string
    {
        return $this->accountId;
    }

    /**
     * Sets Account Id.
     *
     * @maps account_id
     */
    public function setAccountId(?string $accountId): void
    {
        $this->accountId = $accountId;
    }

    /**
     * Converts the EnterprisePayerRequest object to a human-readable string representation.
     *
     * @return string The string representation of the EnterprisePayerRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EnterprisePayerRequest',
            [
                'role' => $this->role,
                'federationId' => $this->federationId,
                'accountId' => $this->accountId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['role', 'federation_id', 'account_id'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['role']              = $this->role;
        if (isset($this->federationId)) {
            $json['federation_id'] = $this->federationId;
        }
        if (isset($this->accountId)) {
            $json['account_id']    = $this->accountId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
