<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class GuestModeRequest implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $enable;

    /**
     * @param bool $enable
     */
    public function __construct(bool $enable)
    {
        $this->enable = $enable;
    }

    /**
     * Returns Enable.
     * Enable or disable Guest Mode
     */
    public function getEnable(): bool
    {
        return $this->enable;
    }

    /**
     * Sets Enable.
     * Enable or disable Guest Mode
     *
     * @required
     * @maps enable
     */
    public function setEnable(bool $enable): void
    {
        $this->enable = $enable;
    }

    /**
     * Converts the GuestModeRequest object to a human-readable string representation.
     *
     * @return string The string representation of the GuestModeRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GuestModeRequest',
            ['enable' => $this->enable, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['enable'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['enable'] = $this->enable;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
