<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * OAuth 2 scopes supported by the API
 */
class OAuthScopeThirdpartytoken
{
    /**
     * Allow Tesla customers to sign in to the application with their Tesla credentials.
     */
    public const OPENID = 'openid';

    /**
     * Allow getting a refresh token without needing user to log in again.
     */
    public const OFFLINE_ACCESS = 'offline_access';

    /**
     * Contact information, home address, profile picture, and referral information.
     */
    public const USER_DATA = 'user_data';

    /**
     * Allow access to your vehicle’s live data, service history, service scheduling data, service
     * communications, eligible upgrades, nearby Superchargers and ownership details.
     */
    public const VEHICLE_DEVICE_DATA = 'vehicle_device_data';

    /**
     * Allow access to vehicle location information, including precise and coarse location data.
     */
    public const VEHICLE_LOCATION = 'vehicle_location';

    /**
     * Commands like add/remove driver, access Live Camera, unlock, wake up, remote start, and schedule
     * software updates.
     */
    public const VEHICLE_CMDS = 'vehicle_cmds';

    /**
     * Vehicle charging history, billed amount, charging location, and commands to schedule, start, or stop
     * charging.
     */
    public const VEHICLE_CHARGING_CMDS = 'vehicle_charging_cmds';

    /**
     * Access detailed vehicle specifications. Partner tokens only; usable without owner authorization.
     */
    public const VEHICLE_SPECS = 'vehicle_specs';

    /**
     * Energy live status, site info, backup history, energy history, and charge history.
     */
    public const ENERGY_DEVICE_DATA = 'energy_device_data';

    /**
     * Update energy settings like backup reserve percent, operation mode, and storm mode.
     */
    public const ENERGY_CMDS = 'energy_cmds';

    /**
     * Allow access to enterprise management functions for businesses.
     */
    public const ENTERPRISE_MANAGEMENT = 'enterprise_management';

    private const _ALL_VALUES = [
        self::OPENID,
        self::OFFLINE_ACCESS,
        self::USER_DATA,
        self::VEHICLE_DEVICE_DATA,
        self::VEHICLE_LOCATION,
        self::VEHICLE_CMDS,
        self::VEHICLE_CHARGING_CMDS,
        self::VEHICLE_SPECS,
        self::ENERGY_DEVICE_DATA,
        self::ENERGY_CMDS,
        self::ENTERPRISE_MANAGEMENT
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OAuthScopeThirdpartytoken.");
    }
}
