<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class OrdersResponse implements \JsonSerializable
{
    /**
     * @var ResponseOrdersResponse[]
     */
    private $response;

    /**
     * @var int
     */
    private $count;

    /**
     * @param ResponseOrdersResponse[] $response
     * @param int $count
     */
    public function __construct(array $response, int $count)
    {
        $this->response = $response;
        $this->count = $count;
    }

    /**
     * Returns Response.
     *
     * @return ResponseOrdersResponse[]
     */
    public function getResponse(): array
    {
        return $this->response;
    }

    /**
     * Sets Response.
     *
     * @required
     * @maps response
     *
     * @param ResponseOrdersResponse[] $response
     */
    public function setResponse(array $response): void
    {
        $this->response = $response;
    }

    /**
     * Returns Count.
     */
    public function getCount(): int
    {
        return $this->count;
    }

    /**
     * Sets Count.
     *
     * @required
     * @maps count
     */
    public function setCount(int $count): void
    {
        $this->count = $count;
    }

    /**
     * Converts the OrdersResponse object to a human-readable string representation.
     *
     * @return string The string representation of the OrdersResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrdersResponse',
            [
                'response' => $this->response,
                'count' => $this->count,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['response', 'count'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['response'] = $this->response;
        $json['count']    = $this->count;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
