<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class Pagination implements \JsonSerializable
{
    /**
     * @var array
     */
    private $previous = [];

    /**
     * @var array
     */
    private $next = [];

    /**
     * @var int|null
     */
    private $current;

    /**
     * @var int|null
     */
    private $perPage;

    /**
     * @var int|null
     */
    private $count;

    /**
     * @var int|null
     */
    private $pages;

    /**
     * Returns Previous.
     */
    public function getPrevious(): ?int
    {
        if (count($this->previous) == 0) {
            return null;
        }
        return $this->previous['value'];
    }

    /**
     * Sets Previous.
     *
     * @maps previous
     */
    public function setPrevious(?int $previous): void
    {
        $this->previous['value'] = $previous;
    }

    /**
     * Unsets Previous.
     */
    public function unsetPrevious(): void
    {
        $this->previous = [];
    }

    /**
     * Returns Next.
     */
    public function getNext(): ?int
    {
        if (count($this->next) == 0) {
            return null;
        }
        return $this->next['value'];
    }

    /**
     * Sets Next.
     *
     * @maps next
     */
    public function setNext(?int $next): void
    {
        $this->next['value'] = $next;
    }

    /**
     * Unsets Next.
     */
    public function unsetNext(): void
    {
        $this->next = [];
    }

    /**
     * Returns Current.
     */
    public function getCurrent(): ?int
    {
        return $this->current;
    }

    /**
     * Sets Current.
     *
     * @maps current
     */
    public function setCurrent(?int $current): void
    {
        $this->current = $current;
    }

    /**
     * Returns Per Page.
     */
    public function getPerPage(): ?int
    {
        return $this->perPage;
    }

    /**
     * Sets Per Page.
     *
     * @maps per_page
     */
    public function setPerPage(?int $perPage): void
    {
        $this->perPage = $perPage;
    }

    /**
     * Returns Count.
     */
    public function getCount(): ?int
    {
        return $this->count;
    }

    /**
     * Sets Count.
     *
     * @maps count
     */
    public function setCount(?int $count): void
    {
        $this->count = $count;
    }

    /**
     * Returns Pages.
     */
    public function getPages(): ?int
    {
        return $this->pages;
    }

    /**
     * Sets Pages.
     *
     * @maps pages
     */
    public function setPages(?int $pages): void
    {
        $this->pages = $pages;
    }

    /**
     * Converts the Pagination object to a human-readable string representation.
     *
     * @return string The string representation of the Pagination object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Pagination',
            [
                'previous' => $this->getPrevious(),
                'next' => $this->getNext(),
                'current' => $this->current,
                'perPage' => $this->perPage,
                'count' => $this->count,
                'pages' => $this->pages,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['previous', 'next', 'current', 'per_page', 'count', 'pages'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->previous)) {
            $json['previous'] = $this->previous['value'];
        }
        if (!empty($this->next)) {
            $json['next']     = $this->next['value'];
        }
        if (isset($this->current)) {
            $json['current']  = $this->current;
        }
        if (isset($this->perPage)) {
            $json['per_page'] = $this->perPage;
        }
        if (isset($this->count)) {
            $json['count']    = $this->count;
        }
        if (isset($this->pages)) {
            $json['pages']    = $this->pages;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
