<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;
use TeslaFleetManagementApiLib\Utils\DateTimeHelper;

class ResponseRegisterPartnerResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $clientId;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string
     */
    private $domain;

    /**
     * @var array
     */
    private $ca = [];

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var string
     */
    private $enterpriseTier;

    /**
     * @var string
     */
    private $accountId;

    /**
     * @var array
     */
    private $issuer = [];

    /**
     * @var array
     */
    private $csr = [];

    /**
     * @var array
     */
    private $csrUpdatedAt = [];

    /**
     * @var string
     */
    private $publicKey;

    /**
     * @var string
     */
    private $publicKeyHash;

    /**
     * @param string $clientId
     * @param string $name
     * @param string $domain
     * @param \DateTime $createdAt
     * @param \DateTime $updatedAt
     * @param string $enterpriseTier
     * @param string $accountId
     * @param string $publicKey
     * @param string $publicKeyHash
     */
    public function __construct(
        string $clientId,
        string $name,
        string $domain,
        \DateTime $createdAt,
        \DateTime $updatedAt,
        string $enterpriseTier,
        string $accountId,
        string $publicKey,
        string $publicKeyHash
    ) {
        $this->clientId = $clientId;
        $this->name = $name;
        $this->domain = $domain;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->enterpriseTier = $enterpriseTier;
        $this->accountId = $accountId;
        $this->publicKey = $publicKey;
        $this->publicKeyHash = $publicKeyHash;
    }

    /**
     * Returns Client Id.
     */
    public function getClientId(): string
    {
        return $this->clientId;
    }

    /**
     * Sets Client Id.
     *
     * @required
     * @maps client_id
     */
    public function setClientId(string $clientId): void
    {
        $this->clientId = $clientId;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Domain.
     */
    public function getDomain(): string
    {
        return $this->domain;
    }

    /**
     * Sets Domain.
     *
     * @required
     * @maps domain
     */
    public function setDomain(string $domain): void
    {
        $this->domain = $domain;
    }

    /**
     * Returns Ca.
     */
    public function getCa(): ?string
    {
        if (count($this->ca) == 0) {
            return null;
        }
        return $this->ca['value'];
    }

    /**
     * Sets Ca.
     *
     * @maps ca
     */
    public function setCa(?string $ca): void
    {
        $this->ca['value'] = $ca;
    }

    /**
     * Unsets Ca.
     */
    public function unsetCa(): void
    {
        $this->ca = [];
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Enterprise Tier.
     */
    public function getEnterpriseTier(): string
    {
        return $this->enterpriseTier;
    }

    /**
     * Sets Enterprise Tier.
     *
     * @required
     * @maps enterprise_tier
     */
    public function setEnterpriseTier(string $enterpriseTier): void
    {
        $this->enterpriseTier = $enterpriseTier;
    }

    /**
     * Returns Account Id.
     */
    public function getAccountId(): string
    {
        return $this->accountId;
    }

    /**
     * Sets Account Id.
     *
     * @required
     * @maps account_id
     */
    public function setAccountId(string $accountId): void
    {
        $this->accountId = $accountId;
    }

    /**
     * Returns Issuer.
     */
    public function getIssuer(): ?string
    {
        if (count($this->issuer) == 0) {
            return null;
        }
        return $this->issuer['value'];
    }

    /**
     * Sets Issuer.
     *
     * @maps issuer
     */
    public function setIssuer(?string $issuer): void
    {
        $this->issuer['value'] = $issuer;
    }

    /**
     * Unsets Issuer.
     */
    public function unsetIssuer(): void
    {
        $this->issuer = [];
    }

    /**
     * Returns Csr.
     */
    public function getCsr(): ?string
    {
        if (count($this->csr) == 0) {
            return null;
        }
        return $this->csr['value'];
    }

    /**
     * Sets Csr.
     *
     * @maps csr
     */
    public function setCsr(?string $csr): void
    {
        $this->csr['value'] = $csr;
    }

    /**
     * Unsets Csr.
     */
    public function unsetCsr(): void
    {
        $this->csr = [];
    }

    /**
     * Returns Csr Updated At.
     */
    public function getCsrUpdatedAt(): ?\DateTime
    {
        if (count($this->csrUpdatedAt) == 0) {
            return null;
        }
        return $this->csrUpdatedAt['value'];
    }

    /**
     * Sets Csr Updated At.
     *
     * @maps csr_updated_at
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCsrUpdatedAt(?\DateTime $csrUpdatedAt): void
    {
        $this->csrUpdatedAt['value'] = $csrUpdatedAt;
    }

    /**
     * Unsets Csr Updated At.
     */
    public function unsetCsrUpdatedAt(): void
    {
        $this->csrUpdatedAt = [];
    }

    /**
     * Returns Public Key.
     */
    public function getPublicKey(): string
    {
        return $this->publicKey;
    }

    /**
     * Sets Public Key.
     *
     * @required
     * @maps public_key
     */
    public function setPublicKey(string $publicKey): void
    {
        $this->publicKey = $publicKey;
    }

    /**
     * Returns Public Key Hash.
     */
    public function getPublicKeyHash(): string
    {
        return $this->publicKeyHash;
    }

    /**
     * Sets Public Key Hash.
     *
     * @required
     * @maps public_key_hash
     */
    public function setPublicKeyHash(string $publicKeyHash): void
    {
        $this->publicKeyHash = $publicKeyHash;
    }

    /**
     * Converts the ResponseRegisterPartnerResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseRegisterPartnerResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseRegisterPartnerResponse',
            [
                'clientId' => $this->clientId,
                'name' => $this->name,
                'description' => $this->description,
                'domain' => $this->domain,
                'ca' => $this->getCa(),
                'createdAt' => $this->createdAt,
                'updatedAt' => $this->updatedAt,
                'enterpriseTier' => $this->enterpriseTier,
                'accountId' => $this->accountId,
                'issuer' => $this->getIssuer(),
                'csr' => $this->getCsr(),
                'csrUpdatedAt' => $this->getCsrUpdatedAt(),
                'publicKey' => $this->publicKey,
                'publicKeyHash' => $this->publicKeyHash,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'client_id',
        'name',
        'description',
        'domain',
        'ca',
        'created_at',
        'updated_at',
        'enterprise_tier',
        'account_id',
        'issuer',
        'csr',
        'csr_updated_at',
        'public_key',
        'public_key_hash'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['client_id']          = $this->clientId;
        $json['name']               = $this->name;
        if (isset($this->description)) {
            $json['description']    = $this->description;
        }
        $json['domain']             = $this->domain;
        if (!empty($this->ca)) {
            $json['ca']             = $this->ca['value'];
        }
        $json['created_at']         = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        $json['updated_at']         = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        $json['enterprise_tier']    = $this->enterpriseTier;
        $json['account_id']         = $this->accountId;
        if (!empty($this->issuer)) {
            $json['issuer']         = $this->issuer['value'];
        }
        if (!empty($this->csr)) {
            $json['csr']            = $this->csr['value'];
        }
        if (!empty($this->csrUpdatedAt)) {
            $json['csr_updated_at'] = DateTimeHelper::toRfc3339DateTime($this->csrUpdatedAt['value']);
        }
        $json['public_key']         = $this->publicKey;
        $json['public_key_hash']    = $this->publicKeyHash;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
