<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;
use TeslaFleetManagementApiLib\Utils\DateTimeHelper;

class ResponseLiveStatusResponse implements \JsonSerializable
{
    /**
     * @var float
     */
    private $solarPower;

    /**
     * @var float
     */
    private $energyLeft;

    /**
     * @var float
     */
    private $totalPackEnergy;

    /**
     * @var float
     */
    private $percentageCharged;

    /**
     * @var bool
     */
    private $backupCapable;

    /**
     * @var float|null
     */
    private $batteryPower;

    /**
     * @var float|null
     */
    private $loadPower;

    /**
     * @var string|null
     */
    private $gridStatus;

    /**
     * @var float|null
     */
    private $gridPower;

    /**
     * @var string|null
     */
    private $islandStatus;

    /**
     * @var bool|null
     */
    private $stormModeActive;

    /**
     * @var \DateTime|null
     */
    private $timestamp;

    /**
     * @param float $solarPower
     * @param float $energyLeft
     * @param float $totalPackEnergy
     * @param float $percentageCharged
     * @param bool $backupCapable
     */
    public function __construct(
        float $solarPower,
        float $energyLeft,
        float $totalPackEnergy,
        float $percentageCharged,
        bool $backupCapable
    ) {
        $this->solarPower = $solarPower;
        $this->energyLeft = $energyLeft;
        $this->totalPackEnergy = $totalPackEnergy;
        $this->percentageCharged = $percentageCharged;
        $this->backupCapable = $backupCapable;
    }

    /**
     * Returns Solar Power.
     */
    public function getSolarPower(): float
    {
        return $this->solarPower;
    }

    /**
     * Sets Solar Power.
     *
     * @required
     * @maps solar_power
     */
    public function setSolarPower(float $solarPower): void
    {
        $this->solarPower = $solarPower;
    }

    /**
     * Returns Energy Left.
     */
    public function getEnergyLeft(): float
    {
        return $this->energyLeft;
    }

    /**
     * Sets Energy Left.
     *
     * @required
     * @maps energy_left
     */
    public function setEnergyLeft(float $energyLeft): void
    {
        $this->energyLeft = $energyLeft;
    }

    /**
     * Returns Total Pack Energy.
     */
    public function getTotalPackEnergy(): float
    {
        return $this->totalPackEnergy;
    }

    /**
     * Sets Total Pack Energy.
     *
     * @required
     * @maps total_pack_energy
     */
    public function setTotalPackEnergy(float $totalPackEnergy): void
    {
        $this->totalPackEnergy = $totalPackEnergy;
    }

    /**
     * Returns Percentage Charged.
     */
    public function getPercentageCharged(): float
    {
        return $this->percentageCharged;
    }

    /**
     * Sets Percentage Charged.
     *
     * @required
     * @maps percentage_charged
     */
    public function setPercentageCharged(float $percentageCharged): void
    {
        $this->percentageCharged = $percentageCharged;
    }

    /**
     * Returns Backup Capable.
     */
    public function getBackupCapable(): bool
    {
        return $this->backupCapable;
    }

    /**
     * Sets Backup Capable.
     *
     * @required
     * @maps backup_capable
     */
    public function setBackupCapable(bool $backupCapable): void
    {
        $this->backupCapable = $backupCapable;
    }

    /**
     * Returns Battery Power.
     */
    public function getBatteryPower(): ?float
    {
        return $this->batteryPower;
    }

    /**
     * Sets Battery Power.
     *
     * @maps battery_power
     */
    public function setBatteryPower(?float $batteryPower): void
    {
        $this->batteryPower = $batteryPower;
    }

    /**
     * Returns Load Power.
     */
    public function getLoadPower(): ?float
    {
        return $this->loadPower;
    }

    /**
     * Sets Load Power.
     *
     * @maps load_power
     */
    public function setLoadPower(?float $loadPower): void
    {
        $this->loadPower = $loadPower;
    }

    /**
     * Returns Grid Status.
     */
    public function getGridStatus(): ?string
    {
        return $this->gridStatus;
    }

    /**
     * Sets Grid Status.
     *
     * @maps grid_status
     */
    public function setGridStatus(?string $gridStatus): void
    {
        $this->gridStatus = $gridStatus;
    }

    /**
     * Returns Grid Power.
     */
    public function getGridPower(): ?float
    {
        return $this->gridPower;
    }

    /**
     * Sets Grid Power.
     *
     * @maps grid_power
     */
    public function setGridPower(?float $gridPower): void
    {
        $this->gridPower = $gridPower;
    }

    /**
     * Returns Island Status.
     */
    public function getIslandStatus(): ?string
    {
        return $this->islandStatus;
    }

    /**
     * Sets Island Status.
     *
     * @maps island_status
     */
    public function setIslandStatus(?string $islandStatus): void
    {
        $this->islandStatus = $islandStatus;
    }

    /**
     * Returns Storm Mode Active.
     */
    public function getStormModeActive(): ?bool
    {
        return $this->stormModeActive;
    }

    /**
     * Sets Storm Mode Active.
     *
     * @maps storm_mode_active
     */
    public function setStormModeActive(?bool $stormModeActive): void
    {
        $this->stormModeActive = $stormModeActive;
    }

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimestamp(?\DateTime $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Converts the ResponseLiveStatusResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseLiveStatusResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseLiveStatusResponse',
            [
                'solarPower' => $this->solarPower,
                'energyLeft' => $this->energyLeft,
                'totalPackEnergy' => $this->totalPackEnergy,
                'percentageCharged' => $this->percentageCharged,
                'backupCapable' => $this->backupCapable,
                'batteryPower' => $this->batteryPower,
                'loadPower' => $this->loadPower,
                'gridStatus' => $this->gridStatus,
                'gridPower' => $this->gridPower,
                'islandStatus' => $this->islandStatus,
                'stormModeActive' => $this->stormModeActive,
                'timestamp' => $this->timestamp,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'solar_power',
        'energy_left',
        'total_pack_energy',
        'percentage_charged',
        'backup_capable',
        'battery_power',
        'load_power',
        'grid_status',
        'grid_power',
        'island_status',
        'storm_mode_active',
        'timestamp'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['solar_power']           = $this->solarPower;
        $json['energy_left']           = $this->energyLeft;
        $json['total_pack_energy']     = $this->totalPackEnergy;
        $json['percentage_charged']    = $this->percentageCharged;
        $json['backup_capable']        = $this->backupCapable;
        if (isset($this->batteryPower)) {
            $json['battery_power']     = $this->batteryPower;
        }
        if (isset($this->loadPower)) {
            $json['load_power']        = $this->loadPower;
        }
        if (isset($this->gridStatus)) {
            $json['grid_status']       = $this->gridStatus;
        }
        if (isset($this->gridPower)) {
            $json['grid_power']        = $this->gridPower;
        }
        if (isset($this->islandStatus)) {
            $json['island_status']     = $this->islandStatus;
        }
        if (isset($this->stormModeActive)) {
            $json['storm_mode_active'] = $this->stormModeActive;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']         = DateTimeHelper::toRfc3339DateTime($this->timestamp);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
