<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ResponseCalendarHistoryResponse implements \JsonSerializable
{
    /**
     * @var Event[]
     */
    private $events;

    /**
     * @var int
     */
    private $totalEvents;

    /**
     * @param Event[] $events
     * @param int $totalEvents
     */
    public function __construct(array $events, int $totalEvents)
    {
        $this->events = $events;
        $this->totalEvents = $totalEvents;
    }

    /**
     * Returns Events.
     *
     * @return Event[]
     */
    public function getEvents(): array
    {
        return $this->events;
    }

    /**
     * Sets Events.
     *
     * @required
     * @maps events
     *
     * @param Event[] $events
     */
    public function setEvents(array $events): void
    {
        $this->events = $events;
    }

    /**
     * Returns Total Events.
     */
    public function getTotalEvents(): int
    {
        return $this->totalEvents;
    }

    /**
     * Sets Total Events.
     *
     * @required
     * @maps total_events
     */
    public function setTotalEvents(int $totalEvents): void
    {
        $this->totalEvents = $totalEvents;
    }

    /**
     * Converts the ResponseCalendarHistoryResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseCalendarHistoryResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseCalendarHistoryResponse',
            [
                'events' => $this->events,
                'totalEvents' => $this->totalEvents,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['events', 'total_events'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['events']       = $this->events;
        $json['total_events'] = $this->totalEvents;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
