<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ResponseMeResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $fullName;

    /**
     * @var string
     */
    private $profileImageUrl;

    /**
     * @var string
     */
    private $vaultUuid;

    /**
     * @param string $email
     * @param string $fullName
     * @param string $profileImageUrl
     * @param string $vaultUuid
     */
    public function __construct(string $email, string $fullName, string $profileImageUrl, string $vaultUuid)
    {
        $this->email = $email;
        $this->fullName = $fullName;
        $this->profileImageUrl = $profileImageUrl;
        $this->vaultUuid = $vaultUuid;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @required
     * @maps email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Full Name.
     */
    public function getFullName(): string
    {
        return $this->fullName;
    }

    /**
     * Sets Full Name.
     *
     * @required
     * @maps full_name
     */
    public function setFullName(string $fullName): void
    {
        $this->fullName = $fullName;
    }

    /**
     * Returns Profile Image Url.
     */
    public function getProfileImageUrl(): string
    {
        return $this->profileImageUrl;
    }

    /**
     * Sets Profile Image Url.
     *
     * @required
     * @maps profile_image_url
     */
    public function setProfileImageUrl(string $profileImageUrl): void
    {
        $this->profileImageUrl = $profileImageUrl;
    }

    /**
     * Returns Vault Uuid.
     */
    public function getVaultUuid(): string
    {
        return $this->vaultUuid;
    }

    /**
     * Sets Vault Uuid.
     *
     * @required
     * @maps vault_uuid
     */
    public function setVaultUuid(string $vaultUuid): void
    {
        $this->vaultUuid = $vaultUuid;
    }

    /**
     * Converts the ResponseMeResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseMeResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseMeResponse',
            [
                'email' => $this->email,
                'fullName' => $this->fullName,
                'profileImageUrl' => $this->profileImageUrl,
                'vaultUuid' => $this->vaultUuid,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['email', 'full_name', 'profile_image_url', 'vault_uuid'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['email']             = $this->email;
        $json['full_name']         = $this->fullName;
        $json['profile_image_url'] = $this->profileImageUrl;
        $json['vault_uuid']        = $this->vaultUuid;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
