<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ResponseRegionResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $region;

    /**
     * @var string
     */
    private $fleetApiBaseUrl;

    /**
     * @param string $region
     * @param string $fleetApiBaseUrl
     */
    public function __construct(string $region, string $fleetApiBaseUrl)
    {
        $this->region = $region;
        $this->fleetApiBaseUrl = $fleetApiBaseUrl;
    }

    /**
     * Returns Region.
     */
    public function getRegion(): string
    {
        return $this->region;
    }

    /**
     * Sets Region.
     *
     * @required
     * @maps region
     */
    public function setRegion(string $region): void
    {
        $this->region = $region;
    }

    /**
     * Returns Fleet Api Base Url.
     */
    public function getFleetApiBaseUrl(): string
    {
        return $this->fleetApiBaseUrl;
    }

    /**
     * Sets Fleet Api Base Url.
     *
     * @required
     * @maps fleet_api_base_url
     */
    public function setFleetApiBaseUrl(string $fleetApiBaseUrl): void
    {
        $this->fleetApiBaseUrl = $fleetApiBaseUrl;
    }

    /**
     * Converts the ResponseRegionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseRegionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseRegionResponse',
            [
                'region' => $this->region,
                'fleetApiBaseUrl' => $this->fleetApiBaseUrl,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['region', 'fleet_api_base_url'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['region']             = $this->region;
        $json['fleet_api_base_url'] = $this->fleetApiBaseUrl;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
