<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class Response3 implements \JsonSerializable
{
    /**
     * @var ChargingLocation[]|null
     */
    private $destinationCharging;

    /**
     * @var ChargingLocation[]|null
     */
    private $superchargers;

    /**
     * @var int|null
     */
    private $timestamp;

    /**
     * Returns Destination Charging.
     *
     * @return ChargingLocation[]|null
     */
    public function getDestinationCharging(): ?array
    {
        return $this->destinationCharging;
    }

    /**
     * Sets Destination Charging.
     *
     * @maps destination_charging
     *
     * @param ChargingLocation[]|null $destinationCharging
     */
    public function setDestinationCharging(?array $destinationCharging): void
    {
        $this->destinationCharging = $destinationCharging;
    }

    /**
     * Returns Superchargers.
     *
     * @return ChargingLocation[]|null
     */
    public function getSuperchargers(): ?array
    {
        return $this->superchargers;
    }

    /**
     * Sets Superchargers.
     *
     * @maps superchargers
     *
     * @param ChargingLocation[]|null $superchargers
     */
    public function setSuperchargers(?array $superchargers): void
    {
        $this->superchargers = $superchargers;
    }

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): ?int
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     */
    public function setTimestamp(?int $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Converts the Response3 object to a human-readable string representation.
     *
     * @return string The string representation of the Response3 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Response3',
            [
                'destinationCharging' => $this->destinationCharging,
                'superchargers' => $this->superchargers,
                'timestamp' => $this->timestamp,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['destination_charging', 'superchargers', 'timestamp'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->destinationCharging)) {
            $json['destination_charging'] = $this->destinationCharging;
        }
        if (isset($this->superchargers)) {
            $json['superchargers']        = $this->superchargers;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']            = $this->timestamp;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
