<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class ResponseChargeHistoryResponse implements \JsonSerializable
{
    /**
     * @var ChargeHistory[]
     */
    private $chargeHistory;

    /**
     * @param ChargeHistory[] $chargeHistory
     */
    public function __construct(array $chargeHistory)
    {
        $this->chargeHistory = $chargeHistory;
    }

    /**
     * Returns Charge History.
     *
     * @return ChargeHistory[]
     */
    public function getChargeHistory(): array
    {
        return $this->chargeHistory;
    }

    /**
     * Sets Charge History.
     *
     * @required
     * @maps charge_history
     *
     * @param ChargeHistory[] $chargeHistory
     */
    public function setChargeHistory(array $chargeHistory): void
    {
        $this->chargeHistory = $chargeHistory;
    }

    /**
     * Converts the ResponseChargeHistoryResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseChargeHistoryResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseChargeHistoryResponse',
            ['chargeHistory' => $this->chargeHistory, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['charge_history'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['charge_history'] = $this->chargeHistory;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
