<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class Response2 implements \JsonSerializable
{
    /**
     * @var Signaling
     */
    private $signaling;

    /**
     * @param Signaling $signaling
     */
    public function __construct(Signaling $signaling)
    {
        $this->signaling = $signaling;
    }

    /**
     * Returns Signaling.
     */
    public function getSignaling(): Signaling
    {
        return $this->signaling;
    }

    /**
     * Sets Signaling.
     *
     * @required
     * @maps signaling
     */
    public function setSignaling(Signaling $signaling): void
    {
        $this->signaling = $signaling;
    }

    /**
     * Converts the Response2 object to a human-readable string representation.
     *
     * @return string The string representation of the Response2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Response2',
            ['signaling' => $this->signaling, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['signaling'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['signaling'] = $this->signaling;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
