<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class Signaling implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $enabled;

    /**
     * @var bool
     */
    private $subscribeConnectivity;

    /**
     * @var bool
     */
    private $useAuthToken;

    /**
     * @param bool $enabled
     * @param bool $subscribeConnectivity
     * @param bool $useAuthToken
     */
    public function __construct(bool $enabled, bool $subscribeConnectivity, bool $useAuthToken)
    {
        $this->enabled = $enabled;
        $this->subscribeConnectivity = $subscribeConnectivity;
        $this->useAuthToken = $useAuthToken;
    }

    /**
     * Returns Enabled.
     */
    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * Sets Enabled.
     *
     * @required
     * @maps enabled
     */
    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    /**
     * Returns Subscribe Connectivity.
     */
    public function getSubscribeConnectivity(): bool
    {
        return $this->subscribeConnectivity;
    }

    /**
     * Sets Subscribe Connectivity.
     *
     * @required
     * @maps subscribe_connectivity
     */
    public function setSubscribeConnectivity(bool $subscribeConnectivity): void
    {
        $this->subscribeConnectivity = $subscribeConnectivity;
    }

    /**
     * Returns Use Auth Token.
     */
    public function getUseAuthToken(): bool
    {
        return $this->useAuthToken;
    }

    /**
     * Sets Use Auth Token.
     *
     * @required
     * @maps use_auth_token
     */
    public function setUseAuthToken(bool $useAuthToken): void
    {
        $this->useAuthToken = $useAuthToken;
    }

    /**
     * Converts the Signaling object to a human-readable string representation.
     *
     * @return string The string representation of the Signaling object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Signaling',
            [
                'enabled' => $this->enabled,
                'subscribeConnectivity' => $this->subscribeConnectivity,
                'useAuthToken' => $this->useAuthToken,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['enabled', 'subscribe_connectivity', 'use_auth_token'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['enabled']                = $this->enabled;
        $json['subscribe_connectivity'] = $this->subscribeConnectivity;
        $json['use_auth_token']         = $this->useAuthToken;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
