<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class TariffElement implements \JsonSerializable
{
    /**
     * @var PriceComponent[]|null
     */
    private $priceComponents;

    /**
     * @var array|null
     */
    private $restrictions;

    /**
     * Returns Price Components.
     *
     * @return PriceComponent[]|null
     */
    public function getPriceComponents(): ?array
    {
        return $this->priceComponents;
    }

    /**
     * Sets Price Components.
     *
     * @maps price_components
     *
     * @param PriceComponent[]|null $priceComponents
     */
    public function setPriceComponents(?array $priceComponents): void
    {
        $this->priceComponents = $priceComponents;
    }

    /**
     * Returns Restrictions.
     */
    public function getRestrictions(): ?array
    {
        return $this->restrictions;
    }

    /**
     * Sets Restrictions.
     *
     * @maps restrictions
     */
    public function setRestrictions(?array $restrictions): void
    {
        $this->restrictions = $restrictions;
    }

    /**
     * Converts the TariffElement object to a human-readable string representation.
     *
     * @return string The string representation of the TariffElement object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TariffElement',
            [
                'priceComponents' => $this->priceComponents,
                'restrictions' => $this->restrictions,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['price_components', 'restrictions'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->priceComponents)) {
            $json['price_components'] = $this->priceComponents;
        }
        if (isset($this->restrictions)) {
            $json['restrictions']     = $this->restrictions;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
