<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class TotalCost implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $exclVat;

    /**
     * @var float|null
     */
    private $inclVat;

    /**
     * @var float|null
     */
    private $vat;

    /**
     * Returns Excl Vat.
     */
    public function getExclVat(): ?float
    {
        return $this->exclVat;
    }

    /**
     * Sets Excl Vat.
     *
     * @maps excl_vat
     */
    public function setExclVat(?float $exclVat): void
    {
        $this->exclVat = $exclVat;
    }

    /**
     * Returns Incl Vat.
     */
    public function getInclVat(): ?float
    {
        return $this->inclVat;
    }

    /**
     * Sets Incl Vat.
     *
     * @maps incl_vat
     */
    public function setInclVat(?float $inclVat): void
    {
        $this->inclVat = $inclVat;
    }

    /**
     * Returns Vat.
     */
    public function getVat(): ?float
    {
        return $this->vat;
    }

    /**
     * Sets Vat.
     *
     * @maps vat
     */
    public function setVat(?float $vat): void
    {
        $this->vat = $vat;
    }

    /**
     * Converts the TotalCost object to a human-readable string representation.
     *
     * @return string The string representation of the TotalCost object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TotalCost',
            [
                'exclVat' => $this->exclVat,
                'inclVat' => $this->inclVat,
                'vat' => $this->vat,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['excl_vat', 'incl_vat', 'vat'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->exclVat)) {
            $json['excl_vat'] = $this->exclVat;
        }
        if (isset($this->inclVat)) {
            $json['incl_vat'] = $this->inclVat;
        }
        if (isset($this->vat)) {
            $json['vat']      = $this->vat;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
