<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class VehicleOption implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $code;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var array
     */
    private $colorCode = [];

    /**
     * @var bool|null
     */
    private $isActive;

    /**
     * Returns Code.
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Display Name.
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     *
     * @maps displayName
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Color Code.
     */
    public function getColorCode(): ?string
    {
        if (count($this->colorCode) == 0) {
            return null;
        }
        return $this->colorCode['value'];
    }

    /**
     * Sets Color Code.
     *
     * @maps colorCode
     */
    public function setColorCode(?string $colorCode): void
    {
        $this->colorCode['value'] = $colorCode;
    }

    /**
     * Unsets Color Code.
     */
    public function unsetColorCode(): void
    {
        $this->colorCode = [];
    }

    /**
     * Returns Is Active.
     */
    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    /**
     * Sets Is Active.
     *
     * @maps isActive
     */
    public function setIsActive(?bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    /**
     * Converts the VehicleOption object to a human-readable string representation.
     *
     * @return string The string representation of the VehicleOption object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VehicleOption',
            [
                'code' => $this->code,
                'displayName' => $this->displayName,
                'colorCode' => $this->getColorCode(),
                'isActive' => $this->isActive,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['code', 'displayName', 'colorCode', 'isActive'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->code)) {
            $json['code']        = $this->code;
        }
        if (isset($this->displayName)) {
            $json['displayName'] = $this->displayName;
        }
        if (!empty($this->colorCode)) {
            $json['colorCode']   = $this->colorCode['value'];
        }
        if (isset($this->isActive)) {
            $json['isActive']    = $this->isActive;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
