<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;

class VehicleBase implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $id;

    /**
     * @var int|null
     */
    private $vehicleId;

    /**
     * @var string|null
     */
    private $vin;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var string|null
     */
    private $accessType;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var bool|null
     */
    private $inService;

    /**
     * @var bool|null
     */
    private $calendarEnabled;

    /**
     * Returns Id.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Vehicle Id.
     */
    public function getVehicleId(): ?int
    {
        return $this->vehicleId;
    }

    /**
     * Sets Vehicle Id.
     *
     * @maps vehicle_id
     */
    public function setVehicleId(?int $vehicleId): void
    {
        $this->vehicleId = $vehicleId;
    }

    /**
     * Returns Vin.
     */
    public function getVin(): ?string
    {
        return $this->vin;
    }

    /**
     * Sets Vin.
     *
     * @maps vin
     */
    public function setVin(?string $vin): void
    {
        $this->vin = $vin;
    }

    /**
     * Returns Display Name.
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     *
     * @maps display_name
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Access Type.
     */
    public function getAccessType(): ?string
    {
        return $this->accessType;
    }

    /**
     * Sets Access Type.
     *
     * @maps access_type
     */
    public function setAccessType(?string $accessType): void
    {
        $this->accessType = $accessType;
    }

    /**
     * Returns State.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns In Service.
     */
    public function getInService(): ?bool
    {
        return $this->inService;
    }

    /**
     * Sets In Service.
     *
     * @maps in_service
     */
    public function setInService(?bool $inService): void
    {
        $this->inService = $inService;
    }

    /**
     * Returns Calendar Enabled.
     */
    public function getCalendarEnabled(): ?bool
    {
        return $this->calendarEnabled;
    }

    /**
     * Sets Calendar Enabled.
     *
     * @maps calendar_enabled
     */
    public function setCalendarEnabled(?bool $calendarEnabled): void
    {
        $this->calendarEnabled = $calendarEnabled;
    }

    /**
     * Converts the VehicleBase object to a human-readable string representation.
     *
     * @return string The string representation of the VehicleBase object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VehicleBase',
            [
                'id' => $this->id,
                'vehicleId' => $this->vehicleId,
                'vin' => $this->vin,
                'displayName' => $this->displayName,
                'accessType' => $this->accessType,
                'state' => $this->state,
                'inService' => $this->inService,
                'calendarEnabled' => $this->calendarEnabled,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'vehicle_id',
        'vin',
        'display_name',
        'access_type',
        'state',
        'in_service',
        'calendar_enabled'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->vehicleId)) {
            $json['vehicle_id']       = $this->vehicleId;
        }
        if (isset($this->vin)) {
            $json['vin']              = $this->vin;
        }
        if (isset($this->displayName)) {
            $json['display_name']     = $this->displayName;
        }
        if (isset($this->accessType)) {
            $json['access_type']      = $this->accessType;
        }
        if (isset($this->state)) {
            $json['state']            = $this->state;
        }
        if (isset($this->inService)) {
            $json['in_service']       = $this->inService;
        }
        if (isset($this->calendarEnabled)) {
            $json['calendar_enabled'] = $this->calendarEnabled;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
