<?php

declare(strict_types=1);

/*
 * TeslaFleetManagementApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TeslaFleetManagementApiLib\Models;

use stdClass;
use TeslaFleetManagementApiLib\ApiHelper;
use TeslaFleetManagementApiLib\Utils\DateTimeHelper;

class WarrantyItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $warrantyType;

    /**
     * @var string|null
     */
    private $warrantyDisplayName;

    /**
     * @var \DateTime|null
     */
    private $expirationDate;

    /**
     * @var int|null
     */
    private $expirationOdometer;

    /**
     * @var string|null
     */
    private $odometerUnit;

    /**
     * @var array
     */
    private $warrantyExpiredOn = [];

    /**
     * @var int|null
     */
    private $coverageAgeInYears;

    /**
     * Returns Warranty Type.
     */
    public function getWarrantyType(): ?string
    {
        return $this->warrantyType;
    }

    /**
     * Sets Warranty Type.
     *
     * @maps warrantyType
     */
    public function setWarrantyType(?string $warrantyType): void
    {
        $this->warrantyType = $warrantyType;
    }

    /**
     * Returns Warranty Display Name.
     */
    public function getWarrantyDisplayName(): ?string
    {
        return $this->warrantyDisplayName;
    }

    /**
     * Sets Warranty Display Name.
     *
     * @maps warrantyDisplayName
     */
    public function setWarrantyDisplayName(?string $warrantyDisplayName): void
    {
        $this->warrantyDisplayName = $warrantyDisplayName;
    }

    /**
     * Returns Expiration Date.
     */
    public function getExpirationDate(): ?\DateTime
    {
        return $this->expirationDate;
    }

    /**
     * Sets Expiration Date.
     *
     * @maps expirationDate
     * @factory \TeslaFleetManagementApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpirationDate(?\DateTime $expirationDate): void
    {
        $this->expirationDate = $expirationDate;
    }

    /**
     * Returns Expiration Odometer.
     */
    public function getExpirationOdometer(): ?int
    {
        return $this->expirationOdometer;
    }

    /**
     * Sets Expiration Odometer.
     *
     * @maps expirationOdometer
     */
    public function setExpirationOdometer(?int $expirationOdometer): void
    {
        $this->expirationOdometer = $expirationOdometer;
    }

    /**
     * Returns Odometer Unit.
     */
    public function getOdometerUnit(): ?string
    {
        return $this->odometerUnit;
    }

    /**
     * Sets Odometer Unit.
     *
     * @maps odometerUnit
     */
    public function setOdometerUnit(?string $odometerUnit): void
    {
        $this->odometerUnit = $odometerUnit;
    }

    /**
     * Returns Warranty Expired On.
     */
    public function getWarrantyExpiredOn(): ?string
    {
        if (count($this->warrantyExpiredOn) == 0) {
            return null;
        }
        return $this->warrantyExpiredOn['value'];
    }

    /**
     * Sets Warranty Expired On.
     *
     * @maps warrantyExpiredOn
     */
    public function setWarrantyExpiredOn(?string $warrantyExpiredOn): void
    {
        $this->warrantyExpiredOn['value'] = $warrantyExpiredOn;
    }

    /**
     * Unsets Warranty Expired On.
     */
    public function unsetWarrantyExpiredOn(): void
    {
        $this->warrantyExpiredOn = [];
    }

    /**
     * Returns Coverage Age in Years.
     */
    public function getCoverageAgeInYears(): ?int
    {
        return $this->coverageAgeInYears;
    }

    /**
     * Sets Coverage Age in Years.
     *
     * @maps coverageAgeInYears
     */
    public function setCoverageAgeInYears(?int $coverageAgeInYears): void
    {
        $this->coverageAgeInYears = $coverageAgeInYears;
    }

    /**
     * Converts the WarrantyItem object to a human-readable string representation.
     *
     * @return string The string representation of the WarrantyItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WarrantyItem',
            [
                'warrantyType' => $this->warrantyType,
                'warrantyDisplayName' => $this->warrantyDisplayName,
                'expirationDate' => $this->expirationDate,
                'expirationOdometer' => $this->expirationOdometer,
                'odometerUnit' => $this->odometerUnit,
                'warrantyExpiredOn' => $this->getWarrantyExpiredOn(),
                'coverageAgeInYears' => $this->coverageAgeInYears,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'warrantyType',
        'warrantyDisplayName',
        'expirationDate',
        'expirationOdometer',
        'odometerUnit',
        'warrantyExpiredOn',
        'coverageAgeInYears'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->warrantyType)) {
            $json['warrantyType']        = $this->warrantyType;
        }
        if (isset($this->warrantyDisplayName)) {
            $json['warrantyDisplayName'] = $this->warrantyDisplayName;
        }
        if (isset($this->expirationDate)) {
            $json['expirationDate']      = DateTimeHelper::toRfc3339DateTime($this->expirationDate);
        }
        if (isset($this->expirationOdometer)) {
            $json['expirationOdometer']  = $this->expirationOdometer;
        }
        if (isset($this->odometerUnit)) {
            $json['odometerUnit']        = $this->odometerUnit;
        }
        if (!empty($this->warrantyExpiredOn)) {
            $json['warrantyExpiredOn']   = $this->warrantyExpiredOn['value'];
        }
        if (isset($this->coverageAgeInYears)) {
            $json['coverageAgeInYears']  = $this->coverageAgeInYears;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
